// plugins/withAndroidRawPropsJsiValueFix.js
//
// Works around a real crash on every Android device: tapping "Add Story" →
// choose Camera aborts the JS thread with
//   "Exception in HostFunction: PreviewView.previewOutput: Cannot cast
//   dynamic to a jsi::Value type. Please use the 'useRawPropsJsiValue'
//   feature flag to enable jsi::Value support for RawValues."
//
// Root cause (confirmed against react-native-vision-camera@5.2.2 +
// react-native-nitro-modules on React Native 0.81.5 — see
// github.com/margelo/nitro/issues/1572, closed as "expected, apps must
// enable this flag themselves; a library cannot enable it for you"):
// any Nitro-generated HybridView (vision-camera's <Camera>/<PreviewView>
// included) reads its props as a jsi::Value, but RN 0.81 only stores a
// jsi::Value inside RawValue when the `useRawPropsJsiValue` feature flag
// is on — it defaults to false and ships with no JS-level override.
//
// This app is a fully managed Expo project (android/ and ios/ are
// gitignored, regenerated by prebuild), so the only durable place to set
// a native feature flag is a config plugin, not a hand-edited
// MainApplication.kt that prebuild would overwrite.
//
// The flag can only be set natively, and only once — a second call to
// ReactNativeFeatureFlags.override() throws ("Feature flags cannot be
// overridden more than once"), and Expo's own loadReactNative(this) call
// already does the first one. dangerouslyForceOverride() sidesteps that
// by swapping in a brand-new accessor instead of mutating the existing
// one, and is safe here because it runs immediately after
// loadReactNative(this) — before any view has mounted or read a flag.
//
// The replacement provider replicates every override
// ReactNativeFeatureFlagsOverrides_RNOSS_Stable_Android(true, true, true)
// would have set (that class is `final` in Kotlin, so it can't be
// subclassed directly) plus the one extra flag this app actually needs.
// Only scoped to Android — this exact crash has only been reproduced on
// real Android devices; iOS behaves differently in testing so far and is
// left alone rather than risk an unverified change there.
const { withMainApplication } = require('expo/config-plugins');

const IMPORT_MARKER = 'import com.facebook.react.ReactNativeApplicationEntryPoint.loadReactNative';
const CALL_MARKER = 'loadReactNative(this)';

const EXTRA_IMPORTS = `${IMPORT_MARKER}
import com.facebook.react.internal.featureflags.ReactNativeFeatureFlags
import com.facebook.react.internal.featureflags.ReactNativeNewArchitectureFeatureFlagsDefaults`;

const PATCH_CALL = `${CALL_MARKER}
    // See plugins/withAndroidRawPropsJsiValueFix.js for why this exists.
    ReactNativeFeatureFlags.dangerouslyForceOverride(
      object : ReactNativeNewArchitectureFeatureFlagsDefaults(true) {
        override fun useFabricInterop(): Boolean = true
        override fun useShadowNodeStateOnClone(): Boolean = true
        override fun useRawPropsJsiValue(): Boolean = true
      }
    )`;

module.exports = function withAndroidRawPropsJsiValueFix(config) {
  return withMainApplication(config, (config) => {
    let { contents } = config.modResults;

    if (contents.includes('useRawPropsJsiValue')) {
      return config; // already patched
    }
    if (!contents.includes(IMPORT_MARKER) || !contents.includes(CALL_MARKER)) {
      throw new Error(
        'withAndroidRawPropsJsiValueFix: expected MainApplication.kt markers not found — ' +
        'the Expo/React Native template changed, update this plugin.'
      );
    }

    contents = contents.replace(IMPORT_MARKER, EXTRA_IMPORTS);
    contents = contents.replace(CALL_MARKER, PATCH_CALL);
    config.modResults.contents = contents;
    return config;
  });
};
