// src/context/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect } from 'react';
import { storage } from '../utils/secureStorage';
import { STORAGE_KEYS } from '../config/constants';

type Lang = 'en' | 'od';

// Port all translations from web LanguageContext exactly
const translations = {
  en: {
    nav: {
      home: 'Home', explore: 'Explore', groups: 'Groups',
      events: 'Events', messages: 'Messages', notifications: 'Notifications',
      members: 'Members', gallery: 'Gallery', profile: 'Profile', settings: 'Settings',
    },
    common: {
      appName: 'Pandara Samaja', appTagline: 'COMMUNITY PORTAL',
      logout: 'Logout', collapse: 'Collapse', expand: 'Expand',
      loading: 'Loading...', error: 'Something went wrong',
      cancel: 'Cancel', save: 'Save', reset: 'Reset', delete: 'Delete',
      retry: 'Retry', ok: 'OK', back: '← Back',
      errorTitle: 'Error', successTitle: 'Success',
      comingSoon: 'Coming in Phase 2',
      loadErrorMessage: 'Could not load content. Check your connection and try again.',
      globalSearchPlaceholder: 'Search members, posts, tags…',
      searching: 'Searching…',
      topResults: 'Top Results',
      securityCheckTitle: 'Security Check in Progress',
      securityCheckMessage: 'Please wait a moment while we establish a secure connection.',
    },
    feed: {
      noPostsTitle: 'No posts yet', noPostsSubtitle: 'Be the first to share something',
      loadError: 'Failed to load community feed.',
      commentError: 'Failed to submit comment.', replyError: 'Failed to submit reply.',
      postError: 'Failed to submit post.', deleteError: 'Failed to delete post.',
      editError: 'Failed to update post.', reportError: 'Failed to submit report.',
      reportSuccessTitle: 'Report Submitted',
      reportSuccessMessage: 'Thank you for keeping our community safe. We will review this post.',
      storySuccessMessage: 'Story uploaded successfully!', storyError: 'Failed to upload story.',
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all read',
      allCaughtUpTitle: 'All caught up', allCaughtUpSubtitle: 'No new notifications',
      loadError: 'Failed to load notifications',
    },
    chat: {
      title: 'Direct Messages',
      searchPlaceholder: 'Search conversations...',
      noConversationsTitle: 'No Conversations',
      noConversationsSubtitle: 'Start a chat from the member directory to connect.',
      online: 'Online', offline: 'Offline',
      messagePlaceholder: 'Type a message...',
      loadError: 'Failed to load conversations.', sendError: 'Failed to send message.',
    },
    settings: {
      title: 'Settings',
      preferencesHeader: 'Preferences',
      pushNotifTitle: 'Push Notifications', pushNotifDesc: 'Alerts for posts, likes & replies',
      eventRemindersTitle: 'Event Reminders', eventRemindersDesc: 'Notifications for upcoming events',
      emailUpdatesTitle: 'Email Updates', emailUpdatesDesc: 'Monthly newsletters & summaries',
      appearanceHeader: 'Appearance',
      themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System',
      languageHeader: 'Language', activeLanguage: 'Active language',
      helpSupportHeader: 'Help & Support',
      whatsappSupport: 'WhatsApp Support',
      privacyPolicy: 'Privacy Policy', termsOfService: 'Terms of Service',
      accountHeader: 'Account', logoutButton: 'Logout',
      confirmLogoutTitle: 'Confirm Logout',
      confirmLogoutMessage: 'Are you sure you want to log out of your account?',
      supportAlertMessage: 'Connecting to WhatsApp Support... (+91 99999 99999)',
      footerName: 'Nikhila Odisha Pandara Samaja',
    },
    auth: {
      memberLoginTitle: 'Member Login',
      membershipNumberLabel: 'Membership Number', membershipPlaceholder: 'e.g. MEM1234567',
      mobileNumberLabel: 'Mobile Number', mobilePlaceholder: '10-digit mobile number',
      sendOtpButton: 'Send OTP',
      membershipRequiredError: 'Please enter your Membership Number',
      mobileRequiredError: 'Please enter a valid 10-digit mobile number',
      sendOtpError: 'Failed to send OTP. Please try again.',
      whatsappNotInstalled: 'WhatsApp is not installed on your device',
      helpSupportTitle: 'Help & Support',
      noMembershipNo: "Don't have a Membership No.?", getOnWhatsapp: 'Get it on WhatsApp →',
      updateMobileNo: 'Need to register/update Mobile No.?', updateOnWhatsapp: 'Update on WhatsApp →',
      notAMemberYet: 'New here? Not a member yet?', contactToRegister: 'Contact us on WhatsApp to register →',
      termsFooter: 'By logging in, you agree to our Terms & Privacy Policy',
      enterOtpTitle: 'Enter OTP', otpSentTo: 'OTP sent to',
      verifyButton: 'Verify & Login',
      invalidOtpError: 'Invalid OTP. Please try again.',
      resendOtpIn: 'Resend OTP in', resendOtp: 'Resend OTP',
    },
    onboarding: {
      slide1Title: 'Welcome to Pandara Samaja',
      slide1Body: 'Connect with 10,000+ members of the Nikhila Odisha Pandara Samaja community across Odisha.',
      slide2Title: 'Your Family, Connected',
      slide2Body: 'Explore the community member directory. Follow, message, and stay connected with your people.',
      slide3Title: 'Stay Informed',
      slide3Body: 'Get community announcements, event updates, leader news, and matrimony listings — all in one place.',
      slide4Title: 'Members Only',
      slide4Body: 'Login with your registered mobile number. Your data is secure and only visible to community members.',
      skip: 'Skip', next: 'Next →', getStarted: 'Get Started',
    },
    announcements: {
      title: 'Announcements',
      officialUpdate: 'Official Update',
      defaultTitle: 'Official Announcement',
      loadError: 'Failed to load official announcements.',
      emptyTitle: 'No Announcements Yet',
      emptySubtitle: 'Check back later for official updates from the admins.',
    },
    events: {
      title: 'Events',
      communityEvents: 'Community Events',
      calendarSubtitle: 'ସମାଜ କାର୍ଯ୍ୟକ୍ରମ — Events Calendar',
      loadError: 'Failed to load community events.',
      rsvpSuccessTitle: 'RSVP Registered',
      rsvpSuccessMessage: 'Successfully registered for this event!',
      rsvpError: 'Failed to submit RSVP registration.',
      tabUpcoming: 'Upcoming', tabPast: 'Past Events', tabRsvped: 'My RSVPs',
      locationTBA: 'TBA',
      attending: 'attending',
      registered: '✓ Registered',
      rsvpNow: 'RSVP Now',
      noRsvpsTitle: 'No RSVPs', noRsvpsSubtitle: "You haven't RSVPed to any events yet.",
      noUpcomingTitle: 'No upcoming events', noUpcomingSubtitle: 'Check back later',
    },
    groups: {
      title: 'Community Groups',
      loadError: 'Failed to fetch groups',
      joinedTitle: 'Joined Group!', leftTitle: 'Left Group!',
      joinedMessagePrefix: 'You are now a member of', joinedMessageSuffix: '',
      leftMessagePrefix: 'You left', leftMessageSuffix: '',
      searchPlaceholder: 'Search groups...',
      verifiedGroup: 'Verified Group',
      joined: 'Joined ✓', joinGroup: 'Join Group',
      emptyTitle: 'No Groups Found', emptySubtitle: 'Try adjusting your search query or categories.',
      showAllGroups: 'Show All Groups',
      categoryAll: 'All Groups', categoryRegional: 'Regional', categoryMatrimony: 'Matrimony',
      categoryYouth: 'Youth', categorySocial: 'Social', categoryProfessional: 'Professional',
    },
    leaders: {
      title: 'Leaders',
      communityLeaders: 'Community Leaders',
      leadershipSubtitle: 'ସମାଜ ନେତୃତ୍ୱ — Leadership Tiers',
      levelState: 'State', levelStateOr: 'ରାଜ୍ୟ',
      levelDistrict: 'District', levelDistrictOr: 'ଜିଲ୍ଲା',
      levelTaluka: 'Taluka', levelTalukaOr: 'ତାଲୁକ',
      levelPanchayat: 'Panchayat', levelPanchayatOr: 'ପଞ୍ଚାୟତ',
      locationPrefix: 'Location:', selectPrefix: 'Select', choose: 'Choose ▾',
      loadingLeaders: 'Loading leaders…',
      emptyTitle: 'No leaders found', emptySubtitle: 'No leader cards have been registered under this tier.',
      selectLocationTitle: 'Select Location', allPrefix: 'All',
      searchPlaceholder: 'Search by name, role, or location…',
      noSearchResultsTitle: 'No matching leaders', noSearchResultsSubtitle: 'Try a different name, role, or location.',
    },
    matrimony: {
      title: 'Matrimony Services',
      verifiedBanner: 'All matrimony profiles are 100% verified by Samaja.',
      filterAll: 'All Candidates', filterBrides: 'Brides ♀', filterGrooms: 'Grooms ♂',
      groomTag: 'Groom ♂', brideTag: 'Bride ♀',
      gotraLabel: 'Gotra:',
      interestExpressedCard: 'Interest Expressed', interestExpressedModal: 'Interest Expressed ✓',
      emptyTitle: 'No Profiles Found', emptySubtitle: 'No profiles match your current selection filter.',
      resetFilter: 'Reset Filter',
      profileDetailsHeader: 'Profile Details',
      heightLabel: 'Height', educationLabel: 'Education', occupationLabel: 'Occupation',
      parentsLabel: 'Parents / Guardians', locationLabel: 'Location',
      yearsAbbrev: 'yrs',
      sendInterest: 'Send Interest',
      shortlistAddedTitle: 'Added to Shortlist', shortlistRemovedTitle: 'Removed from Shortlist',
      shortlistAddedMessagePrefix: 'You have shortlisted', shortlistAddedMessageSuffix: '',
      shortlistRemovedMessagePrefix: 'You removed', shortlistRemovedMessageSuffix: 'from shortlist',
      interestExpressedToastTitle: 'Interest Expressed!', interestRetractedToastTitle: 'Interest Retracted',
      interestExpressedMessagePrefix: 'A request has been sent to', interestExpressedMessageSuffix: "'s family.",
      interestCanceledMessagePrefix: 'You canceled interest in', interestCanceledMessageSuffix: '',
      // Tabs
      tabBrowse: 'Browse', tabMyProfile: 'My Profile', tabMatches: 'Matches',
      // Search / filter / sort
      searchPlaceholder: 'Search by name, education, gotra…',
      sortLabel: 'Sort', sortNewest: 'Newest', sortAgeAsc: 'Age ↑', sortAgeDesc: 'Age ↓', sortName: 'Name',
      filterButtonLabel: 'Filters',
      filtersTitle: 'Search & Filter',
      minAgeLabel: 'Min Age', maxAgeLabel: 'Max Age',
      educationFilterLabel: 'Education', educationFilterPlaceholder: 'e.g. B.Tech, MBA…',
      gotraFilterLabel: 'Gotra', gotraFilterPlaceholder: 'e.g. Kashyap…',
      genderFilterLabel: 'Show',
      applyFiltersButton: 'Apply Filters', resetFiltersButton: 'Reset',
      loadError: 'Failed to load matrimony candidates.',
      // Candidate card / detail
      banshaLabel: 'Bansha', bloodGroupLabel: 'Blood Group',
      technicalEducationLabel: 'Technical Education', professionalEducationLabel: 'Professional Education',
      fatherLabel: 'Father', motherLabel: 'Mother', addressLabel: 'Address',
      phoneLabel: 'Phone', emailLabel: 'Email',
      viewBiodataButton: 'View Biodata Form', noBiodataForm: 'No biodata form uploaded',
      likeButtonLabel: 'Like', passButtonLabel: 'Pass',
      swipeError: 'Failed to record your response. Please try again.',
      matchedAlertTitle: "It's a Match!", matchedAlertMessage: 'You both showed interest in each other. Check the Matches tab to connect.',
      // My profile
      myProfileHeader: 'My Matrimony Profile',
      noProfileTitle: 'No Profile Submitted', noProfileSubtitle: 'Create your matrimony profile so other members can discover you.',
      createProfileButton: 'Create Your Profile', editProfileButton: 'Edit Profile',
      createFormTitle: 'Create Your Profile', editFormTitle: 'Edit Your Profile',
      nameFieldLabel: 'Full Name', namePlaceholder: 'Full name',
      genderFieldLabel: 'Gender', maleOption: 'Male', femaleOption: 'Female',
      dobLabel: 'Date of Birth', dobPlaceholder: 'YYYY-MM-DD',
      ageFieldLabel: 'Age', ageFieldPlaceholder: 'Age in years',
      heightPlaceholder: 'e.g. 5\'8"',
      bloodGroupPlaceholder: 'e.g. O+',
      banshaPlaceholder: 'Bansha / clan',
      educationPlaceholder: 'e.g. B.Tech Computer Science',
      technicalEducationPlaceholder: 'e.g. Diploma, ITI…',
      professionalEducationPlaceholder: 'e.g. CA, CMA…',
      occupationPlaceholder: 'e.g. Software Engineer at TCS',
      fatherPlaceholder: "Father's name",
      motherPlaceholder: "Mother's name",
      addressPlaceholder: 'Village, District…',
      phonePlaceholder: '10-digit mobile number',
      emailPlaceholder: 'email@example.com',
      photosFieldLabel: 'Photos', choosePhotosButton: 'Choose Photos',
      formFieldLabel: 'Biodata Form', chooseFormButton: 'Choose Biodata Document',
      formPickerHelpText: 'Pick a clear photo of your biodata document.',
      submitProfileButton: 'Submit Profile', savingProfileButton: 'Saving…',
      nameRequiredError: "Please enter the candidate's name.",
      genderRequiredError: 'Please select a gender.',
      saveProfileError: 'Failed to save your matrimony profile.',
      saveProfileSuccessTitle: 'Profile Saved', saveProfileSuccessMessage: 'Your matrimony profile has been saved.',
      loadProfileError: 'Failed to load your matrimony profile.',
      // Matches
      matchesHeader: 'Your Matches',
      noMatchesTitle: 'No Matches Yet', noMatchesSubtitle: 'Keep browsing — mutual likes will show up here.',
      loadMatchesError: 'Failed to load your matches.',
      matchedBadge: 'Matched ✓',
    },
    members: {
      title: 'Members',
      loadError: 'Failed to load members',
      searchPlaceholder: 'Name · #no · village · mobile…',
      matchingPrefix: 'matching',
      countSuffix: 'members',
      noMembersTitle: 'No members found',
      noMembersSubtitle: 'Try adjusting your search or filters',
      allLoadedPrefix: 'All', allLoadedSuffix: 'members loaded',
      maleHof: '♂ Male HoF', femaleHof: '♀ Female HoF',
      // Filter modal
      filterModalTitle: 'Filter Members',
      districtSectionTitle: 'District', talukaSectionTitle: 'Taluka',
      panchayatSectionTitle: 'Panchayat', villageSectionTitle: 'Village',
      genderSectionTitle: 'Head of Family Gender',
      allDistricts: 'All Districts',
      allTalukasInPrefix: 'All Talukas in', allPanchayatsInPrefix: 'All Panchayats in', allVillagesInPrefix: 'All Villages in',
      allGenders: 'All Genders', maleHead: '♂ Male Head', femaleHead: '♀ Female Head',
      resetButton: 'Reset',
      showResultsPrefix: 'Show', showResultsSuffix: 'Results',
      // Member card
      activeBadge: 'ACTIVE',
      headGenderTitle: 'Head Gender',
      genderFemaleTag: '♀ Female', genderMaleTag: '♂ Male',
      maleWord: 'Male', femaleWord: 'Female',
      familyMembersListLabel: 'Family Members List',
    },
    memberProfile: {
      notFoundText: 'Profile not found or restricted.',
      returnToMembers: '← Return to Members',
      backLabel: '← Back',
      followingLabel: 'Following', followLabel: 'Follow', messageLabel: 'Message',
      headOfFamily: 'Head of Family',
      joinedPrefix: 'Joined',
      postsTabLabel: 'Posts', familyTabLabel: 'Family', galleryTabLabel: 'Gallery',
      statsFollowersLabel: 'Followers',
      familyMembersHeader: 'Family Members',
      noPostsTitle: 'No posts yet', noPostsSubtitle: "This member hasn't posted yet",
      noPhotosTitle: 'No photos', noPhotosSubtitle: 'No photos shared yet',
    },
    profile: {
      title: 'My Profile',
      settingsButton: 'Settings',
      memberBadge: 'Pandara Member',
      headOfFamily: 'Head of Family',
      mobilePrefix: 'Mobile:',
      familyHubHeader: 'Family Hub',
      familyTreeLabel: 'Family Tree', familyTreeDesc: 'Genealogy tree',
      matrimonyLabel: 'Matrimony', matrimonyDesc: 'Find matches',
      familyAlbumsLabel: 'Family Albums', familyAlbumsDesc: 'Shared gallery',
      familyEventsLabel: 'Family Events', familyEventsDesc: 'Rsvped events',
      leadersLabel: 'Leaders', leadersDesc: 'Community leadership',
      addressInfoHeader: 'Address Information',
      villageLabel: 'Village', panchayatLabel: 'Panchayat', fullAddressLabel: 'Full Address',
      notSpecified: 'Not specified',
      villagePlaceholder: 'Village name', panchayatPlaceholder: 'Panchayat name', addressPlaceholder: 'Full address details',
      familyMembersHeader: 'Family Members',
      noFamilyMembers: 'No family members registered.',
      yrsAbbrev: 'yrs',
      profilePhotoTitle: 'Profile Photo', profilePhotoMessage: 'Change or remove your profile picture.',
      removePhoto: 'Remove Photo', removedTitle: 'Removed', removedMessage: 'Profile photo removed.',
      uploadNewPhoto: 'Choose from Gallery', uploadTitle: 'Upload', uploadMessage: 'Photo upload simulated.',
      takePhoto: 'Take Photo', cameraPermissionDenied: 'Camera access is needed to take a photo.',
      galleryPermissionDenied: 'Photo library access is needed to choose a photo.',
      uploadError: 'Failed to update your profile photo.',
      profileSavedTitle: 'Profile Saved', profileSavedMessage: 'Your address details have been updated.',
    },
    familyTree: {
      title: 'Family Tree',
      subtitle: 'Your family, visualized',
      headOfFamily: 'Head of Family',
      membershipPrefix: 'Membership #',
      groupSpouse: 'Spouse',
      groupParents: 'Parents',
      groupChildren: 'Children',
      groupOthers: 'Other Family Members',
      ageSuffix: 'yrs',
      emptyTitle: 'No Family Data',
      emptySubtitle: 'Your family details have not been added to your profile yet.',
    },
    familyAlbums: {
      title: 'Family Albums',
      subtitle: 'Photos shared within your family',
      loadError: 'Failed to load family albums.',
      createAlbum: 'Create Album',
      newAlbumTitle: 'New Album',
      albumTitleLabel: 'Title',
      albumTitlePlaceholder: 'e.g. Diwali 2025',
      albumDescriptionLabel: 'Description',
      albumDescriptionPlaceholder: 'Add a short description (optional)',
      coverPhotoLabel: 'Cover Photo (optional)',
      chooseCoverPhoto: 'Choose Cover Photo',
      changeCoverPhoto: 'Change Cover Photo',
      createButton: 'Create Album',
      creatingButton: 'Creating…',
      titleRequiredError: 'Please enter an album title.',
      createError: 'Failed to create album.',
      createSuccessTitle: 'Album Created',
      createSuccessMessage: 'Your new family album is ready.',
      photosCountSuffix: 'photos',
      photoCountSingular: 'photo',
      emptyTitle: 'No Albums Yet',
      emptySubtitle: 'Create your first family album to start sharing photos.',
      deleteAlbumConfirmTitle: 'Delete Album',
      deleteAlbumConfirmMessage: 'This will permanently delete this album and all its photos. Continue?',
      deleteError: 'Failed to delete album.',
      deleteSuccessMessage: 'Album deleted.',
      addPhotos: 'Add Photos',
      addingPhotos: 'Uploading…',
      addPhotosError: 'Failed to add photos.',
      addPhotosSuccessMessage: 'Photos added to album.',
      noPhotosInAlbum: 'No photos in this album yet.',
      cancelButton: 'Cancel',
      closeButton: 'Close',
    },
    familyEvents: {
      title: 'Family Events',
      subtitle: 'Events for your own family',
      loadError: 'Failed to load family events.',
      createEvent: 'Create Event',
      newEventTitle: 'New Family Event',
      eventTitleLabel: 'Title',
      eventTitlePlaceholder: "e.g. Grandma's Birthday",
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Add details (optional)',
      dateLabel: 'Date',
      datePlaceholder: 'YYYY-MM-DD',
      locationLabel: 'Location',
      locationPlaceholder: 'Where is it happening?',
      typeLabel: 'Type',
      typePlaceholder: 'e.g. Birthday, Anniversary, Gathering',
      createButton: 'Create Event',
      creatingButton: 'Creating…',
      titleRequiredError: 'Please enter an event title.',
      dateRequiredError: 'Please enter a valid date (YYYY-MM-DD).',
      createError: 'Failed to create event.',
      createSuccessTitle: 'Event Created',
      createSuccessMessage: 'Your family event has been added.',
      emptyTitle: 'No Family Events',
      emptySubtitle: 'Create an event to start planning with your family.',
      deleteEventConfirmTitle: 'Delete Event',
      deleteEventConfirmMessage: 'Are you sure you want to delete this event?',
      deleteError: 'Failed to delete event.',
      deleteSuccessMessage: 'Event deleted.',
      tabUpcoming: 'Upcoming',
      tabPast: 'Past',
      rsvpGoing: 'Going',
      rsvpMaybe: 'Maybe',
      rsvpNotGoing: 'Not Going',
      rsvpError: 'Failed to submit RSVP.',
      locationTBA: 'TBA',
      cancelButton: 'Cancel',
    },
    explore: {
      title: 'Explore',
      tabTrending: 'Trending', tabMembers: 'Members', tabHashtags: 'Hashtags',
      trendingPostsTitle: 'Trending Posts',
      trendingPostsSubtitle: 'Posts with the most engagement across the community. (Coming Soon)',
      activeMembersLabel: 'Total Members Active Today',
      noPopularMembers: 'No popular members data available.',
      noTags: 'No tags available at the moment.',
    },
    feedComponents: {
      warningTitle: 'Warning',
      inappropriateCommentMessage: 'Your comment contains inappropriate content.',
      cancelButtonLabel: 'Cancel',
      saveButtonLabel: 'Save',
      deleteButtonLabel: 'Delete',
      commentWord: 'comment',
      commentsWordPlural: 'comments',
      likeLabel: 'Like',
      likedLabel: 'Liked',
      replyLabel: 'Reply',
      writeReplyPlaceholder: 'Write a reply...',
      noCommentsYetText: 'No comments yet',
      loadMoreCommentsLabel: 'Load more comments',
      writeCommentPlaceholder: 'Write a comment...',
      editPostLabel: 'Edit Post',
      deletePostLabel: 'Delete Post',
      savePostLabel: 'Save Post',
      unsavePostLabel: 'Unsave Post',
      reportPostLabel: 'Report Post',
      deletePostConfirmTitle: 'Delete Post',
      deletePostConfirmMessage: 'Are you sure you want to delete this post?',
      reportPostModalTitle: 'Report Post',
      reportPostPrompt: 'Why are you reporting this post?',
      submitReportLabel: 'Submit Report',
      reportReasonAdult: 'Adult / Sexual content',
      reportReasonHarassment: 'Harassment or bullying',
      reportReasonHateSpeech: 'Hate speech',
      reportReasonSpam: 'Spam or misleading',
      reportReasonViolence: 'Violence or dangerous content',
      reportReasonFalseInfo: 'False information',
      reportReasonOther: 'Other',
      sharePostTitlePrefix: 'Post by',
      genericErrorTitle: 'Error',
      postValidationErrorMessage: 'Please enter some text or add media/poll.',
      inappropriateContentTitle: 'Inappropriate Content',
      inappropriateContentMessage: 'Your post contains banned words.',
      shareSomethingPlaceholder: 'Share something with the community...',
      createPostTitle: 'Create Post',
      postButtonLabel: 'Post',
      postingToMemberPortal: 'Posting to Member Portal',
      whatsOnYourMindPlaceholder: "What's on your mind? (Use #tags or @mentions)",
      enterLocationPlaceholder: 'Enter location tag...',
      createPollTitle: 'Create Poll',
      pollLimitReachedTitle: 'Limit Reached',
      pollLimitReachedMessage: 'You can add up to 5 options.',
      pollMinOptionsTitle: 'Required',
      pollMinOptionsMessage: 'A poll requires at least 2 options.',
      pollQuestionRequiredMessage: 'Please enter a poll question.',
      pollOptionsRequiredMessage: 'Please enter at least 2 valid options.',
      pollQuestionLabel: 'Question',
      pollQuestionPlaceholder: 'What would you like to ask?',
      pollOptionsLabel: 'Options',
      pollOptionPlaceholderPrefix: 'Option',
      addOptionLabel: 'Add Option',
      createButtonLabel: 'Create',
      voteWord: 'vote',
      votesWordPlural: 'votes',
      pollEndsPrefix: 'Ends',
      addStoryLabel: 'Add Story',
    },
    admin: {
      entryLinkLabel: 'Admin Login',
      loginTitle: 'Admin Login',
      loginSubtitle: 'Staff access only',
      usernameLabel: 'Username',
      usernamePlaceholder: 'Enter username',
      passwordLabel: 'Password',
      passwordPlaceholder: 'Enter password',
      loginButton: 'Log In',
      usernameRequiredError: 'Please enter your username',
      passwordRequiredError: 'Please enter your password',
      loginError: 'Invalid username or password',

      dashboardTitle: 'Admin Dashboard',
      roleAdmin: 'Admin',
      roleSuperadmin: 'Super Admin',
      membersCardTitle: 'Members',
      membersCardDesc: 'View, search & manage member accounts',
      reportsCardTitle: 'Reported Posts',
      reportsCardDesc: 'Review flagged content',
      usersCardTitle: 'Manage Admins',
      usersCardDesc: 'Create & remove admin accounts',
      logoutButton: 'Log out of admin',
      confirmLogoutTitle: 'Log Out',
      confirmLogoutMessage: 'Are you sure you want to log out of the admin panel?',

      membersTitle: 'Members',
      membersSearchPlaceholder: 'Search by name, membership no, village…',
      membersLoadError: 'Failed to load members',
      membersEmptyTitle: 'No members found',
      membersEmptySubtitle: 'Try a different search term',
      bannedBadge: 'Banned',
      activeBadge: 'Active',
      banButton: 'Ban Member',
      unbanButton: 'Unban Member',
      confirmBanTitle: 'Ban Member',
      confirmBanMessage: 'This member will be blocked from the app and their content will stay hidden. Continue?',
      confirmUnbanTitle: 'Unban Member',
      confirmUnbanMessage: "Restore this member's access to the app?",
      banError: 'Failed to update member status',

      memberDetailTitle: 'Member Details',
      postsCountLabel: 'Posts',
      reportsAgainstLabel: 'Reports Against',
      reportsFiledLabel: 'Reports Filed',
      memberLoadError: 'Failed to load member',
      memberNotFound: 'Member not found',

      editMemberTitle: 'Edit Member',
      memberEditSaveError: 'Failed to save member',
      memberEditMobileLabel: 'Mobile',
      memberEditDistrictLabel: 'District',
      memberEditTalukaLabel: 'Taluka',
      memberEditPanchayatLabel: 'Panchayat',
      memberEditVillageLabel: 'Village',

      reportsTitle: 'Reported Posts',
      reportsLoadError: 'Failed to load reported posts',
      reportsEmptyTitle: 'All clear',
      reportsEmptySubtitle: 'No posts are pending review',
      reasonLabel: 'Reason',
      approveButton: 'Approve',
      rejectButton: 'Reject',
      confirmRejectTitle: 'Reject Post',
      confirmRejectMessage: 'This will permanently delete the post. This cannot be undone. Continue?',
      moderationActionError: 'Failed to update this post',

      usersTitle: 'Manage Admins',
      usersLoadError: 'Failed to load admin accounts',
      usersEmptyTitle: 'No admin accounts yet',
      newAdminTitle: 'New Admin Account',
      roleFieldLabel: 'Role',
      createButton: 'Create',
      createAdminError: 'Failed to create admin account',
      usernameRequiredCreateError: 'Please enter a username',
      passwordRequiredCreateError: 'Please enter a password',
      removeButton: 'Remove',
      confirmRemoveTitle: 'Remove Admin',
      confirmRemoveMessage: 'Remove this admin account? They will no longer be able to log in.',
      removeError: 'Failed to remove admin account',
      lastLoginLabel: 'Last login',
      neverLabel: 'Never',

      editAdminTitle: 'Edit Admin Account',
      editAdminError: 'Failed to update admin account',
      newPasswordOptionalLabel: 'New Password (optional)',
      newPasswordOptionalPlaceholder: 'Leave blank to keep current password',
      confirmBanAdminTitle: 'Disable Admin Account',
      confirmBanAdminMessage: 'This admin will no longer be able to log in. Continue?',
      confirmUnbanAdminTitle: 'Enable Admin Account',
      confirmUnbanAdminMessage: "Restore this admin's ability to log in?",
      adminStatusError: 'Failed to update admin account status',

      trackerCardTitle: 'Activity Tracker',
      trackerCardDesc: 'Audit trail of member & admin actions',
      matrimonyCardTitle: 'Matrimony',
      matrimonyCardDesc: 'Manage matrimony candidate profiles',
      postsCardTitle: 'Feed Posts',
      postsCardDesc: 'Moderate all community feed posts',
      announcementsCardTitle: 'Announcements',
      announcementsCardDesc: 'Create & manage official announcements',
      expensesCardTitle: 'Expenses',
      expensesCardDesc: 'Track community income & expenses',
      settingsCardTitle: 'Settings',
      settingsCardDesc: 'Change your admin password',
      leadersCardTitle: 'Leaders',
      leadersCardDesc: 'Manage community leader profiles',

      leadersTitle: 'Manage Leaders',
      leadersSearchPlaceholder: 'Search by name or role…',
      leadersLoadError: 'Failed to load leaders',
      leadersEmptyTitle: 'No leaders found',
      leadersEmptySubtitle: 'Tap + to add your first leader',
      leaderCreateTitle: 'New Leader',
      leaderEditTitle: 'Edit Leader',
      leaderNameLabel: 'Name',
      leaderNameOrLabel: 'Name (Odia)',
      leaderRoleLabel: 'Role',
      leaderRoleOrLabel: 'Role (Odia)',
      leaderLevelLabel: 'Level',
      leaderLocationLabel: 'Location',
      leaderLocationPlaceholder: 'e.g. district, block or village name',
      leaderDisplayOrderLabel: 'Display Order',
      leaderDisplayOrderPlaceholder: 'e.g. 1',
      leaderNameRequiredError: 'Please enter a name',
      leaderRoleRequiredError: 'Please enter a role',
      leaderSaveError: 'Failed to save leader',
      leaderDeleteError: 'Failed to delete leader',
      confirmDeleteLeaderTitle: 'Delete Leader',
      confirmDeleteLeaderMessage: 'This will permanently delete this leader profile. Continue?',

      trackerTitle: 'Activity Tracker',
      trackerTargetLabel: 'Target',
      trackerIpLabel: 'IP address',
      trackerDeviceLabel: 'Device',
      trackerFilterAll: 'All',
      trackerFilterMembers: 'Members',
      trackerFilterAdmins: 'Admins',
      trackerMigrationPendingTitle: 'Activity tracking not yet active',
      trackerMigrationPendingSubtitle: 'Activity tracking will begin once a pending update is applied',
      trackerEmptyTitle: 'No activity yet',
      trackerEmptySubtitle: 'Actions will show up here as they happen',
      action_admin_created: 'Admin account created',
      action_admin_deleted: 'Admin account removed',
      action_admin_login: 'Admin logged in',
      action_admin_banned: 'Admin account disabled',
      action_admin_unbanned: 'Admin account enabled',
      action_announcement_created: 'Announcement created',
      action_announcement_deleted: 'Announcement deleted',
      action_announcement_updated: 'Announcement updated',
      action_comment_created: 'Comment posted',
      action_expense_created: 'Expense entry added',
      action_follow_toggled: 'Follow status changed',
      action_login: 'Logged in',
      action_matrimony_profile_admin_created: 'Matrimony profile created by admin',
      action_matrimony_profile_submitted: 'Matrimony profile submitted',
      action_matrimony_swipe: 'Matrimony swipe recorded',
      action_member_banned: 'Member banned',
      action_member_unbanned: 'Member unbanned',
      action_post_created: 'Post created',
      action_post_liked: 'Post liked',
      action_profile_photo_updated: 'Profile photo updated',
      action_report_approved: 'Report approved',
      action_report_rejected: 'Report rejected',

      matrimonyTitle: 'Matrimony Candidates',
      matrimonyAgeSuffix: 'yrs',
      matrimonyApprovedBadge: 'Approved',
      matrimonySearchPlaceholder: 'Search by name, gotra, occupation…',
      matrimonyEmptyTitle: 'No candidates found',
      matrimonyEmptySubtitle: 'Try a different search term',
      matrimonyLoadError: 'Failed to load candidate',
      matrimonyNameRequiredError: 'Please enter a name',
      matrimonySaveError: 'Failed to save candidate profile',
      matrimonyDeleteError: 'Failed to delete candidate profile',
      confirmDeleteCandidateTitle: 'Delete Candidate',
      confirmDeleteCandidateMessage: 'This will permanently delete this candidate profile. This cannot be undone. Continue?',
      matrimonyBanError: 'Failed to update candidate status',
      confirmBanCandidateTitle: 'Ban Candidate',
      confirmBanCandidateMessage: 'This candidate profile will be hidden from the matrimony section. Continue?',
      confirmUnbanCandidateTitle: 'Unban Candidate',
      confirmUnbanCandidateMessage: 'Restore this candidate profile in the matrimony section?',
      matrimonyEditTitle: 'Edit Candidate',
      matrimonyCreateTitle: 'New Candidate',
      matrimonyNameLabel: 'Name',
      matrimonyGenderLabel: 'Gender',
      matrimonyGenderMale: 'Male',
      matrimonyGenderFemale: 'Female',
      matrimonyDobLabel: 'Date of Birth',
      matrimonyAgeLabel: 'Age',
      matrimonyHeightLabel: 'Height',
      matrimonyBloodGroupLabel: 'Blood Group',
      matrimonyGotraLabel: 'Gotra',
      matrimonyBanshaLabel: 'Bansha',
      matrimonyEducationLabel: 'Education',
      matrimonyTechnicalEducationLabel: 'Technical Education',
      matrimonyProfessionalEducationLabel: 'Professional Education',
      matrimonyOccupationLabel: 'Occupation',
      matrimonyFatherLabel: "Father's Name",
      matrimonyMotherLabel: "Mother's Name",
      matrimonyAddressLabel: 'Address',
      matrimonyPhoneLabel: 'Phone',
      matrimonyEmailLabel: 'Email',

      postsTitle: 'Feed Posts',
      postsSearchPlaceholder: 'Search by author or content…',
      postsLoadError: 'Failed to load posts',
      postsEmptyTitle: 'No posts found',
      postsEmptySubtitle: 'Try a different search term',
      postActionError: 'Failed to update post visibility',
      postDeleteError: 'Failed to delete post',
      confirmDeletePostTitle: 'Delete Post',
      confirmDeletePostMessage: 'This will permanently delete the post. This cannot be undone. Continue?',
      postHiddenBadge: 'Hidden',
      postVisibleBadge: 'Visible',
      hideButton: 'Hide',
      unhideButton: 'Unhide',

      announcementsTitle: 'Announcements',
      announcementsLoadError: 'Failed to load announcements',
      announcementsEmptyTitle: 'No announcements yet',
      announcementsEmptySubtitle: 'Tap + to create your first announcement',
      galleryPermissionDenied: 'Gallery access is required to pick media',
      announcementTitleRequiredError: 'Please enter a title',
      announcementSaveError: 'Failed to save announcement',
      announcementDeleteError: 'Failed to delete announcement',
      confirmDeleteAnnouncementTitle: 'Delete Announcement',
      confirmDeleteAnnouncementMessage: 'This will permanently delete this announcement. Continue?',
      editButton: 'Edit',
      editAnnouncementTitle: 'Edit Announcement',
      newAnnouncementTitle: 'New Announcement',
      announcementTitleLabel: 'Title',
      announcementTitlePlaceholder: 'Announcement title',
      announcementContentLabel: 'Content',
      announcementContentPlaceholder: 'Write the announcement details…',
      addImageLabel: 'Add Image',
      replaceImageLabel: 'Replace Image',
      imageSelectedLabel: 'Image Selected',
      addVideoLabel: 'Add Video',
      replaceVideoLabel: 'Replace Video',
      videoSelectedLabel: 'Video Selected',

      expensesTitle: 'Community Expenses',
      expensesLoadError: 'Failed to load expense entries',
      expensesEmptyTitle: 'No entries yet',
      expensesEmptySubtitle: 'Tap + to add an income or expense entry',
      expensesMigrationPendingTitle: 'Expenses tracking not yet active',
      expensesMigrationPendingSubtitle: 'This feature will be available once a pending update is applied',
      expenseFilterAll: 'All',
      expenseFilterIncome: 'Income',
      expenseFilterExpense: 'Expense',
      summaryIncomeLabel: 'Income',
      summaryExpenseLabel: 'Expense',
      summaryBalanceLabel: 'Balance',
      expenseTitleRequiredError: 'Please enter a title',
      expenseAmountRequiredError: 'Please enter a valid amount',
      expenseSaveError: 'Failed to save entry',
      expenseDeleteError: 'Failed to delete entry',
      confirmDeleteExpenseTitle: 'Delete Entry',
      confirmDeleteExpenseMessage: 'This will permanently delete this ledger entry. Continue?',
      editExpenseTitle: 'Edit Entry',
      newExpenseTitle: 'New Entry',
      expenseTitleLabel: 'Title',
      expenseTitlePlaceholder: 'e.g. Annual membership fees',
      expenseAmountLabel: 'Amount (₹)',
      expenseAmountPlaceholder: 'Enter amount',
      expenseCategoryLabel: 'Category (optional)',
      expenseCategoryPlaceholder: 'e.g. Events, Donations',
      expenseDateLabel: 'Date (optional, YYYY-MM-DD)',
      expenseDatePlaceholder: 'e.g. 2026-07-26',
      expenseNoteLabel: 'Note (optional)',
      expenseNotePlaceholder: 'Additional details…',

      settingsTitle: 'Admin Settings',
      accountInfoHeader: 'Account Information',
      changePasswordHeader: 'Change Password',
      currentPasswordLabel: 'Current Password',
      currentPasswordPlaceholder: 'Enter current password',
      newPasswordLabel: 'New Password',
      newPasswordPlaceholder: 'Enter new password',
      confirmPasswordLabel: 'Confirm New Password',
      confirmPasswordPlaceholder: 'Re-enter new password',
      currentPasswordRequiredError: 'Please enter your current password',
      newPasswordTooShortError: 'New password must be at least 6 characters',
      passwordsDontMatchError: 'New password and confirmation do not match',
      passwordChangedSuccess: 'Password updated successfully',
      passwordChangeError: 'Failed to change password',
    },
  },
  od: {
    nav: {
      home: 'ଘର', explore: 'ଅନ୍ୱେଷଣ', groups: 'ଦଳ',
      events: 'ଅନୁଷ୍ଠାନ', messages: 'ବାର୍ତ୍ତା', notifications: 'ବିଜ୍ଞପ୍ତି',
      members: 'ସଦସ୍ୟ', gallery: 'ଗ୍ୟାଲେରୀ', profile: 'ପ୍ରୋଫାଇଲ', settings: 'ସେଟିଂ',
    },
    common: {
      appName: 'ପଣ୍ଡାର ସମାଜ', appTagline: 'ସାମୁଦାୟିକ ପୋର୍ଟାଲ',
      logout: 'ଲଗ୍ ଆଉଟ', collapse: 'ସଂକୁଚିତ', expand: 'ବିସ୍ତାର',
      loading: 'ଲୋଡ ହେଉଛି...', error: 'କିଛି ଭୁଲ ହୋଇଗଲା',
      cancel: 'ବାତିଲ', save: 'ସେଭ୍', reset: 'ପୁନଃସେଟ୍', delete: 'ଡିଲିଟ୍',
      retry: 'ପୁନଃ ଚେଷ୍ଟା', ok: 'ଠିକ୍ ଅଛି', back: '← ପଛକୁ',
      errorTitle: 'ତ୍ରୁଟି', successTitle: 'ସଫଳ',
      comingSoon: 'ପର୍ଯ୍ୟାୟ ୨ ରେ ଆସୁଛି',
      loadErrorMessage: 'ବିଷୟବସ୍ତୁ ଲୋଡ୍ କରିପାରିଲା ନାହିଁ। ଆପଣଙ୍କ ସଂଯୋଗ ଯାଞ୍ଚ କରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      globalSearchPlaceholder: 'ସଦସ୍ୟ, ପୋଷ୍ଟ, ଟ୍ୟାଗ୍ ଖୋଜନ୍ତୁ…',
      searching: 'ଖୋଜୁଛି…',
      topResults: 'ଶୀର୍ଷ ଫଳାଫଳ',
      securityCheckTitle: 'ସୁରକ୍ଷା ଯାଞ୍ଚ ଚାଲୁଛି',
      securityCheckMessage: 'ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ, ଆମେ ଏକ ସୁରକ୍ଷିତ ସଂଯୋଗ ସ୍ଥାପନ କରୁଛୁ।',
    },
    feed: {
      noPostsTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପୋଷ୍ଟ ନାହିଁ', noPostsSubtitle: 'କିଛି ସେୟାର କରିବାରେ ପ୍ରଥମ ହୁଅନ୍ତୁ',
      loadError: 'ସାମୁଦାୟିକ ଫିଡ୍ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      commentError: 'ମନ୍ତବ୍ୟ ଦାଖଲ କରିବାରେ ବିଫଳ।', replyError: 'ଉତ୍ତର ଦାଖଲ କରିବାରେ ବିଫଳ।',
      postError: 'ପୋଷ୍ଟ ଦାଖଲ କରିବାରେ ବିଫଳ।', deleteError: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ।',
      editError: 'ପୋଷ୍ଟ ଅପଡେଟ୍ କରିବାରେ ବିଫଳ।', reportError: 'ରିପୋର୍ଟ ଦାଖଲ କରିବାରେ ବିଫଳ।',
      reportSuccessTitle: 'ରିପୋର୍ଟ ଦାଖଲ ହେଲା',
      reportSuccessMessage: 'ଆମ ସମାଜକୁ ସୁରକ୍ଷିତ ରଖିବାପାଇଁ ଧନ୍ୟବାଦ। ଆମେ ଏହି ପୋଷ୍ଟକୁ ସମୀକ୍ଷା କରିବୁ।',
      storySuccessMessage: 'ଷ୍ଟୋରୀ ସଫଳତାର ସହ ଅପଲୋଡ୍ ହେଲା!', storyError: 'ଷ୍ଟୋରୀ ଅପଲୋଡ୍ କରିବାରେ ବିଫଳ।',
    },
    notifications: {
      title: 'ବିଜ୍ଞପ୍ତି',
      markAllRead: 'ସବୁ ପଢ଼ାଯାଇଛି ବୋଲି ଚିହ୍ନଟ କରନ୍ତୁ',
      allCaughtUpTitle: 'ସବୁ ଦେଖାଗଲା', allCaughtUpSubtitle: 'କୌଣସି ନୂଆ ବିଜ୍ଞପ୍ତି ନାହିଁ',
      loadError: 'ବିଜ୍ଞପ୍ତି ଲୋଡ୍ କରିବାରେ ବିଫଳ',
    },
    chat: {
      title: 'ସନ୍ଦେଶ',
      searchPlaceholder: 'ସନ୍ଦେଶ ବା ସଦସ୍ୟ ଖୋଜନ୍ତୁ...',
      noConversationsTitle: 'କୌଣସି ଆଲାପ ମିଳିଲା ନାହିଁ',
      noConversationsSubtitle: 'ସଦସ୍ୟ ତାଲିକାରୁ ଯାଇ ଚାଟ୍ ଆରମ୍ଭ କରନ୍ତୁ',
      online: 'ଅନଲାଇନ', offline: 'ଅଫଲାଇନ',
      messagePlaceholder: 'ବାର୍ତ୍ତା ଲେଖନ୍ତୁ...',
      loadError: 'ଆଲାପ ଲୋଡ୍ କରିବାରେ ବିଫଳ।', sendError: 'ବାର୍ତ୍ତା ପଠାଇବାରେ ବିଫଳ।',
    },
    settings: {
      title: 'ସେଟିଂ',
      preferencesHeader: 'ପସନ୍ଦ',
      pushNotifTitle: 'ପୁସ୍ ବିଜ୍ଞପ୍ତି', pushNotifDesc: 'ନୂଆ ପୋଷ୍ଟ ଓ ବାର୍ତ୍ତା ପାଇଁ ବିଜ୍ଞପ୍ତି',
      eventRemindersTitle: 'ଅନୁଷ୍ଠାନ ମନେପକାନ୍ତୁ', eventRemindersDesc: 'ଆଗାମୀ ସଭା ଓ ସାମାଜିକ ଅନୁଷ୍ଠାନ',
      emailUpdatesTitle: 'ଇମେଲ ଅପଡେଟ', emailUpdatesDesc: 'ମାସିକ ସମାଚାର ପତ୍ରିକା',
      appearanceHeader: 'ରୂପ',
      themeLight: 'ଆଲୋକ', themeDark: 'ଅନ୍ଧାର', themeSystem: 'ସିଷ୍ଟମ',
      languageHeader: 'ଭାଷା', activeLanguage: 'ସକ୍ରିୟ ଭାଷା',
      helpSupportHeader: 'ସହାୟତା',
      whatsappSupport: 'ହ୍ଵାଟସ୍‌ଆପ୍ ସହାୟତା',
      privacyPolicy: 'ଗୋପନୀୟତା ନୀତି', termsOfService: 'ସେବା ସର୍ତ୍ତାବଳୀ',
      accountHeader: 'ଖାତା', logoutButton: 'ଲଗ୍ ଆଉଟ୍ କରନ୍ତୁ',
      confirmLogoutTitle: 'ଲଗ୍ ଆଉଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
      confirmLogoutMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଲଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      supportAlertMessage: 'ସହାୟତା ସେବା ଶୀଘ୍ର ଉପଲବ୍ଧ ହେବ।',
      footerName: 'ନିଖିଳ ଓଡ଼ିଶା ପଣ୍ଡାର ସମାଜ',
    },
    auth: {
      memberLoginTitle: 'ସଦସ୍ୟ ଲଗଇନ',
      membershipNumberLabel: 'ସଦସ୍ୟତା ନମ୍ବର', membershipPlaceholder: 'ଯଥା MEM1234567',
      mobileNumberLabel: 'ମୋବାଇଲ ନମ୍ବର', mobilePlaceholder: '୧୦-ଅଙ୍କ ମୋବାଇଲ ନମ୍ବର',
      sendOtpButton: 'OTP ପଠାନ୍ତୁ',
      membershipRequiredError: 'ଦୟାକରି ଆପଣଙ୍କର ସଦସ୍ୟତା ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
      mobileRequiredError: 'ଦୟାକରି ଏକ ବୈଧ ୧୦-ଅଙ୍କ ମୋବାଇଲ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
      sendOtpError: 'OTP ପଠାଇବାରେ ବିଫଳ। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      whatsappNotInstalled: 'ଆପଣଙ୍କ ଡିଭାଇସରେ ହ୍ଵାଟସ୍‌ଆପ୍ ଇନଷ୍ଟଲ ହୋଇନାହିଁ',
      helpSupportTitle: 'ସହାୟତା',
      noMembershipNo: 'ସଦସ୍ୟତା ନମ୍ବର ନାହିଁ?', getOnWhatsapp: 'ହ୍ଵାଟସ୍‌ଆପ୍‌ରେ ପାଆନ୍ତୁ →',
      updateMobileNo: 'ମୋବାଇଲ ନମ୍ବର ପଞ୍ଜିକରଣ/ଅପଡେଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି?', updateOnWhatsapp: 'ହ୍ଵାଟସ୍‌ଆପ୍‌ରେ ଅପଡେଟ୍ କରନ୍ତୁ →',
      notAMemberYet: 'ନୂଆ ଆସିଛନ୍ତି? ଏପର୍ଯ୍ୟନ୍ତ ସଦସ୍ୟ ନୁହଁନ୍ତି?', contactToRegister: 'ପଞ୍ଜିକରଣ ପାଇଁ ହ୍ଵାଟସ୍‌ଆପ୍‌ରେ ଯୋଗାଯୋଗ କରନ୍ତୁ →',
      termsFooter: 'ଲଗଇନ କରି, ଆପଣ ଆମର ସର୍ତ୍ତାବଳୀ ଓ ଗୋପନୀୟତା ନୀତିରେ ସହମତ ହେଉଛନ୍ତି',
      enterOtpTitle: 'OTP ପ୍ରବେଶ କରନ୍ତୁ', otpSentTo: 'ଏଠାକୁ OTP ପଠାଗଲା',
      verifyButton: 'ଯାଞ୍ଚ କରନ୍ତୁ ଓ ଲଗଇନ କରନ୍ତୁ',
      invalidOtpError: 'ଅବୈଧ OTP। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      resendOtpIn: 'ପୁନଃ OTP ପଠାଇବାରେ', resendOtp: 'ପୁନଃ OTP ପଠାନ୍ତୁ',
    },
    onboarding: {
      slide1Title: 'ପଣ୍ଡାର ସମାଜକୁ ସ୍ୱାଗତ',
      slide1Body: 'ଓଡ଼ିଶା ଭରିରେ ନିଖିଳ ଓଡ଼ିଶା ପଣ୍ଡାର ସମାଜର ୧୦,୦୦୦+ ସଦସ୍ୟଙ୍କ ସହ ଯୋଡ଼ି ହୁଅନ୍ତୁ।',
      slide2Title: 'ଆପଣଙ୍କ ପରିବାର, ସଂଯୁକ୍ତ',
      slide2Body: 'ସାମୁଦାୟିକ ସଦସ୍ୟ ତାଲିକା ଅନ୍ୱେଷଣ କରନ୍ତୁ। ଅନୁସରଣ କରନ୍ତୁ, ବାର୍ତ୍ତା ପଠାନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ଲୋକଙ୍କ ସହ ସଂଯୁକ୍ତ ରୁହନ୍ତୁ।',
      slide3Title: 'ଖବର ପାଆନ୍ତୁ',
      slide3Body: 'ସାମୁଦାୟିକ ଘୋଷଣା, ଅନୁଷ୍ଠାନ ଅପଡେଟ୍, ନେତାଙ୍କ ସମାଚାର ଏବଂ ବିବାହ ତାଲିକା — ସବୁ ଏକ ସ୍ଥାନରେ ପାଆନ୍ତୁ।',
      slide4Title: 'କେବଳ ସଦସ୍ୟଙ୍କ ପାଇଁ',
      slide4Body: 'ଆପଣଙ୍କ ପଞ୍ଜିକୃତ ମୋବାଇଲ ନମ୍ବର ସହ ଲଗଇନ କରନ୍ତୁ। ଆପଣଙ୍କ ତଥ୍ୟ ସୁରକ୍ଷିତ ଏବଂ କେବଳ ସାମୁଦାୟିକ ସଦସ୍ୟଙ୍କୁ ଦୃଶ୍ୟମାନ।',
      skip: 'ଏଡ଼ାଇ ଦିଅନ୍ତୁ', next: 'ପରବର୍ତ୍ତୀ →', getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
    },
    announcements: {
      title: 'ଘୋଷଣା',
      officialUpdate: 'ସରକାରୀ ଅପଡେଟ୍',
      defaultTitle: 'ସରକାରୀ ଘୋଷଣା',
      loadError: 'ସରକାରୀ ଘୋଷଣା ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      emptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଘୋଷଣା ନାହିଁ',
      emptySubtitle: 'ଆଡମିନଙ୍କ ପକ୍ଷରୁ ସରକାରୀ ଅପଡେଟ୍ ପାଇଁ ପରେ ଯାଞ୍ଚ କରନ୍ତୁ।',
    },
    events: {
      title: 'ଅନୁଷ୍ଠାନ',
      communityEvents: 'ସାମୁଦାୟିକ କାର୍ଯ୍ୟକ୍ରମ',
      calendarSubtitle: 'ସମାଜ କାର୍ଯ୍ୟକ୍ରମ — Events Calendar',
      loadError: 'ସାମୁଦାୟିକ କାର୍ଯ୍ୟକ୍ରମ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      rsvpSuccessTitle: 'RSVP ପଞ୍ଜିକୃତ ହେଲା',
      rsvpSuccessMessage: 'ଏହି କାର୍ଯ୍ୟକ୍ରମ ପାଇଁ ସଫଳତାର ସହ ପଞ୍ଜିକୃତ ହେଲେ!',
      rsvpError: 'RSVP ପଞ୍ଜିକରଣ ଦାଖଲ କରିବାରେ ବିଫଳ।',
      tabUpcoming: 'ଆଗାମୀ', tabPast: 'ପୂର୍ବ କାର୍ଯ୍ୟକ୍ରମ', tabRsvped: 'ମୋର RSVP',
      locationTBA: 'ପରେ ଜଣାଇବେ',
      attending: 'ଉପସ୍ଥିତ',
      registered: '✓ ପଞ୍ଜିକୃତ',
      rsvpNow: 'RSVP କରନ୍ତୁ',
      noRsvpsTitle: 'କୌଣସି RSVP ନାହିଁ', noRsvpsSubtitle: 'ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଯ୍ୟକ୍ରମରେ RSVP କରିନାହାଁନ୍ତି।',
      noUpcomingTitle: 'କୌଣସି ଆଗାମୀ କାର୍ଯ୍ୟକ୍ରମ ନାହିଁ', noUpcomingSubtitle: 'ପରେ ପୁଣି ଯାଞ୍ଚ କରନ୍ତୁ',
    },
    groups: {
      title: 'ସମାଜ ଗ୍ରୁପ୍ ଗୁଡିକ',
      loadError: 'ଗ୍ରୁପ୍ ତାଲିକା ଆଣିବାରେ ବିଫଳ',
      joinedTitle: 'ଗ୍ରୁପ୍‌ରେ ଯୋଗ ଦେଲେ!', leftTitle: 'ଗ୍ରୁପ୍ ଛାଡିଲେ!',
      joinedMessagePrefix: 'ଆପଣ', joinedMessageSuffix: 'ରେ ଯୋଗ ଦେଇଛନ୍ତି',
      leftMessagePrefix: 'ଆପଣ', leftMessageSuffix: 'ରୁ ବାହାରି ଯାଇଛନ୍ତି',
      searchPlaceholder: 'ଗ୍ରୁପ୍ ଖୋଜନ୍ତୁ...',
      verifiedGroup: 'ଯୋଗ୍ୟ ସଦସ୍ୟ',
      joined: 'ଯୋଗଦେଇଛନ୍ତି ✓', joinGroup: 'ଯୋଗ ଦିଅନ୍ତୁ',
      emptyTitle: 'କୌଣସି ଗ୍ରୁପ୍ ମିଳିଲା ନାହିଁ', emptySubtitle: 'ଅନ୍ୟ ସନ୍ଧାନ ସର୍ତ୍ତ ଚେଷ୍ଟା କରନ୍ତୁ',
      showAllGroups: 'ସମସ୍ତ ଗ୍ରୁପ୍ ଦେଖନ୍ତୁ',
      categoryAll: 'ସମସ୍ତ ଗ୍ରୁପ୍', categoryRegional: 'ଆଞ୍ଚଳିକ', categoryMatrimony: 'ବିବାହ',
      categoryYouth: 'ଯୁବକ', categorySocial: 'ସାମାଜିକ', categoryProfessional: 'ପେଶାଦାର',
    },
    leaders: {
      title: 'ନେତା',
      communityLeaders: 'ସମାଜ ନେତା',
      leadershipSubtitle: 'ସମାଜ ନେତୃତ୍ୱ — Leadership Tiers',
      levelState: 'State', levelStateOr: 'ରାଜ୍ୟ',
      levelDistrict: 'District', levelDistrictOr: 'ଜିଲ୍ଲା',
      levelTaluka: 'Taluka', levelTalukaOr: 'ତାଲୁକ',
      levelPanchayat: 'Panchayat', levelPanchayatOr: 'ପଞ୍ଚାୟତ',
      locationPrefix: 'ସ୍ଥାନ:', selectPrefix: 'ମନୋନୀତ କରନ୍ତୁ', choose: 'ମନୋନୀତ କରନ୍ତୁ ▾',
      loadingLeaders: 'ନେତାମାନଙ୍କୁ ଲୋଡ୍ କରାଯାଉଛି…',
      emptyTitle: 'କୌଣସି ନେତା ମିଳିଲେ ନାହିଁ', emptySubtitle: 'ଏହି ସ୍ତରରେ କୌଣସି ନେତା କାର୍ଡ ପଞ୍ଜିକୃତ ହୋଇନାହିଁ।',
      selectLocationTitle: 'ସ୍ଥାନ ମନୋନୀତ କରନ୍ତୁ', allPrefix: 'ସମସ୍ତ',
      searchPlaceholder: 'ନାମ, ପଦବୀ, କିମ୍ବା ସ୍ଥାନ ଅନୁସାରେ ଖୋଜନ୍ତୁ…',
      noSearchResultsTitle: 'କୌଣସି ମେଳ ମିଳିଲା ନାହିଁ', noSearchResultsSubtitle: 'ଅନ୍ୟ ନାମ, ପଦବୀ, କିମ୍ବା ସ୍ଥାନ ଚେଷ୍ଟା କରନ୍ତୁ।',
    },
    matrimony: {
      title: 'ବୈବାହିକ ପ୍ରସ୍ତାବ',
      verifiedBanner: 'ସମସ୍ତ ପ୍ରୋଫାଇଲ୍ ସମାଜ ଦ୍ୱାରା ଯାଞ୍ଚ ହୋଇଛି',
      filterAll: 'ସବୁ', filterBrides: 'ପାତ୍ରୀ ♀', filterGrooms: 'ପାତ୍ର ♂',
      groomTag: 'ପାତ୍ର ♂', brideTag: 'ପାତ୍ରୀ ♀',
      gotraLabel: 'ଗୋତ୍ର:',
      interestExpressedCard: 'ଆଗ୍ରହ ପଠାଯାଇଛି ✓', interestExpressedModal: 'ଆଗ୍ରହ ପଠାଯାଇଛି ✓',
      emptyTitle: 'କୌଣସି ପାତ୍ର/ପାତ୍ରୀ ମିଳିଲେ ନାହିଁ', emptySubtitle: 'ଅନ୍ୟ ଫିଲ୍ଟର ଚେଷ୍ଟା କରନ୍ତୁ',
      resetFilter: 'ଫିଲ୍ଟର୍ ରିସେଟ୍ କରନ୍ତୁ',
      profileDetailsHeader: 'ବ୍ୟକ୍ତିଗତ ବିବରଣୀ',
      heightLabel: 'ଉଚ୍ଚତା', educationLabel: 'ଶିକ୍ଷାଗତ ଯୋଗ୍ୟତା', occupationLabel: 'ବୃତ୍ତି / ଚାକିରି',
      parentsLabel: 'ପିତାମାତାଙ୍କ ପରିଚୟ', locationLabel: 'ସ୍ଥାନ',
      yearsAbbrev: 'ବର୍ଷ',
      sendInterest: 'ଆଗ୍ରହ ପ୍ରକାଶ କରନ୍ତୁ',
      shortlistAddedTitle: 'ପସନ୍ଦ ତାଲିକାରେ ଯୋଡ଼ାଗଲା', shortlistRemovedTitle: 'ପସନ୍ଦ ତାଲିକାରୁ ବାଦ୍ ଦିଆଗଲା',
      shortlistAddedMessagePrefix: '', shortlistAddedMessageSuffix: 'ଙ୍କୁ ଆପଣ ପସନ୍ଦ କରିଛନ୍ତି',
      shortlistRemovedMessagePrefix: '', shortlistRemovedMessageSuffix: 'ଙ୍କୁ ବାଦ୍ ଦିଆଯାଇଛି',
      interestExpressedToastTitle: 'ଆଗ୍ରହ ପ୍ରକାଶ ହେଲା!', interestRetractedToastTitle: 'ଆଗ୍ରହ ପ୍ରତ୍ୟାହାର ହେଲା',
      interestExpressedMessagePrefix: 'ଆପଣଙ୍କ ଅନୁରୋଧ', interestExpressedMessageSuffix: ' ଙ୍କ ପରିବାରକୁ ପଠାଗଲା।',
      interestCanceledMessagePrefix: 'ଆପଣ', interestCanceledMessageSuffix: 'ଙ୍କଠାରେ ଆଗ୍ରହ ପ୍ରତ୍ୟାହାର କଲେ',
      // Tabs
      tabBrowse: 'ଅନ୍ୱେଷଣ', tabMyProfile: 'ମୋ ପ୍ରୋଫାଇଲ୍', tabMatches: 'ମେଳ',
      // Search / filter / sort
      searchPlaceholder: 'ନାମ, ଶିକ୍ଷା, ଗୋତ୍ର ଦ୍ୱାରା ଖୋଜନ୍ତୁ…',
      sortLabel: 'କ୍ରମ', sortNewest: 'ନୂତନ', sortAgeAsc: 'ବୟସ ↑', sortAgeDesc: 'ବୟସ ↓', sortName: 'ନାମ',
      filterButtonLabel: 'ଫିଲ୍ଟର୍',
      filtersTitle: 'ଖୋଜ ଓ ଫିଲ୍ଟର୍',
      minAgeLabel: 'ସର୍ବନିମ୍ନ ବୟସ', maxAgeLabel: 'ସର୍ବାଧିକ ବୟସ',
      educationFilterLabel: 'ଶିକ୍ଷା', educationFilterPlaceholder: 'ଯଥା B.Tech, MBA…',
      gotraFilterLabel: 'ଗୋତ୍ର', gotraFilterPlaceholder: 'ଯଥା କଶ୍ୟପ…',
      genderFilterLabel: 'ଦେଖାନ୍ତୁ',
      applyFiltersButton: 'ଫିଲ୍ଟର୍ ପ୍ରୟୋଗ କରନ୍ତୁ', resetFiltersButton: 'ପୁନଃସେଟ୍',
      loadError: 'ବୈବାହିକ ପ୍ରାର୍ଥୀ ତାଲିକା ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      // Candidate card / detail
      banshaLabel: 'ବଂଶ', bloodGroupLabel: 'ରକ୍ତ ଗୋଷ୍ଠୀ',
      technicalEducationLabel: 'ବୈଷୟିକ ଶିକ୍ଷା', professionalEducationLabel: 'ବୃତ୍ତିଗତ ଶିକ୍ଷା',
      fatherLabel: 'ପିତା', motherLabel: 'ମାତା', addressLabel: 'ଠିକଣା',
      phoneLabel: 'ମୋବାଇଲ', emailLabel: 'ଇମେଲ',
      viewBiodataButton: 'ବାୟୋଡାଟା ଫର୍ମ ଦେଖନ୍ତୁ', noBiodataForm: 'କୌଣସି ବାୟୋଡାଟା ଫର୍ମ ଅପଲୋଡ୍ ହୋଇନାହିଁ',
      likeButtonLabel: 'ପସନ୍ଦ', passButtonLabel: 'ବାଦ୍',
      swipeError: 'ଆପଣଙ୍କ ପ୍ରତିକ୍ରିୟା ଦାଖଲ କରିବାରେ ବିଫଳ। ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      matchedAlertTitle: 'ଏହା ଏକ ମେଳ!', matchedAlertMessage: 'ଆପଣ ଦୁହେଁ ପରସ୍ପର ପ୍ରତି ଆଗ୍ରହ ଦେଖାଇଛନ୍ତି। ଯୋଗାଯୋଗ କରିବାକୁ ମେଳ ଟ୍ୟାବ୍ ଦେଖନ୍ତୁ।',
      // My profile
      myProfileHeader: 'ମୋର ବୈବାହିକ ପ୍ରୋଫାଇଲ୍',
      noProfileTitle: 'କୌଣସି ପ୍ରୋଫାଇଲ୍ ଦାଖଲ ହୋଇନାହିଁ', noProfileSubtitle: 'ଅନ୍ୟ ସଦସ୍ୟମାନେ ଆପଣଙ୍କୁ ଖୋଜିପାରିବା ପାଇଁ ଆପଣଙ୍କର ବୈବାହିକ ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ।',
      createProfileButton: 'ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ', editProfileButton: 'ପ୍ରୋଫାଇଲ୍ ସମ୍ପାଦନ କରନ୍ତୁ',
      createFormTitle: 'ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ତିଆରି କରନ୍ତୁ', editFormTitle: 'ଆପଣଙ୍କର ପ୍ରୋଫାଇଲ୍ ସମ୍ପାଦନ କରନ୍ତୁ',
      nameFieldLabel: 'ପୂରା ନାମ', namePlaceholder: 'ପୂରା ନାମ',
      genderFieldLabel: 'ଲିଙ୍ଗ', maleOption: 'ପୁରୁଷ', femaleOption: 'ମହିଳା',
      dobLabel: 'ଜନ୍ମ ତାରିଖ', dobPlaceholder: 'YYYY-MM-DD',
      ageFieldLabel: 'ବୟସ', ageFieldPlaceholder: 'ବର୍ଷରେ ବୟସ',
      heightPlaceholder: "ଯଥା 5'8\"",
      bloodGroupPlaceholder: 'ଯଥା O+',
      banshaPlaceholder: 'ବଂଶ / ଗୋତ୍ର',
      educationPlaceholder: 'ଯଥା B.Tech କମ୍ପ୍ୟୁଟର ସାଇନ୍ସ',
      technicalEducationPlaceholder: 'ଯଥା ଡିପ୍ଲୋମା, ITI…',
      professionalEducationPlaceholder: 'ଯଥା CA, CMA…',
      occupationPlaceholder: 'ଯଥା ସଫ୍ଟୱେର୍ ଇଞ୍ଜିନିୟର୍',
      fatherPlaceholder: 'ପିତାଙ୍କ ନାମ',
      motherPlaceholder: 'ମାତାଙ୍କ ନାମ',
      addressPlaceholder: 'ଗ୍ରାମ, ଜିଲ୍ଲା…',
      phonePlaceholder: '୧୦-ଅଙ୍କ ମୋବାଇଲ ନମ୍ବର',
      emailPlaceholder: 'email@example.com',
      photosFieldLabel: 'ଫଟୋ', choosePhotosButton: 'ଫଟୋ ମନୋନୀତ କରନ୍ତୁ',
      formFieldLabel: 'ବାୟୋଡାଟା ଫର୍ମ', chooseFormButton: 'ବାୟୋଡାଟା ଡକ୍ୟୁମେଣ୍ଟ ମନୋନୀତ କରନ୍ତୁ',
      formPickerHelpText: 'ଆପଣଙ୍କର ବାୟୋଡାଟା ଡକ୍ୟୁମେଣ୍ଟର ଏକ ସ୍ପଷ୍ଟ ଫଟୋ ମନୋନୀତ କରନ୍ତୁ।',
      submitProfileButton: 'ପ୍ରୋଫାଇଲ୍ ଦାଖଲ କରନ୍ତୁ', savingProfileButton: 'ସେଭ୍ ହେଉଛି…',
      nameRequiredError: 'ଦୟାକରି ପ୍ରାର୍ଥୀଙ୍କ ନାମ ଲେଖନ୍ତୁ।',
      genderRequiredError: 'ଦୟାକରି ଲିଙ୍ଗ ମନୋନୀତ କରନ୍ତୁ।',
      saveProfileError: 'ଆପଣଙ୍କର ବୈବାହିକ ପ୍ରୋଫାଇଲ୍ ସେଭ୍ କରିବାରେ ବିଫଳ।',
      saveProfileSuccessTitle: 'ପ୍ରୋଫାଇଲ୍ ସେଭ୍ ହେଲା', saveProfileSuccessMessage: 'ଆପଣଙ୍କର ବୈବାହିକ ପ୍ରୋଫାଇଲ୍ ସେଭ୍ ହୋଇଛି।',
      loadProfileError: 'ଆପଣଙ୍କର ବୈବାହିକ ପ୍ରୋଫାଇଲ୍ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      // Matches
      matchesHeader: 'ଆପଣଙ୍କର ମେଳ',
      noMatchesTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମେଳ ନାହିଁ', noMatchesSubtitle: 'ଅନ୍ୱେଷଣ ଜାରି ରଖନ୍ତୁ — ପାରସ୍ପରିକ ପସନ୍ଦ ଏଠାରେ ଦେଖାଯିବ।',
      loadMatchesError: 'ଆପଣଙ୍କର ମେଳ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      matchedBadge: 'ମେଳ ✓',
    },
    members: {
      title: 'ସଦସ୍ୟ',
      loadError: 'ସଦସ୍ୟ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      searchPlaceholder: 'ନାମ · #ନମ୍ବର · ଗ୍ରାମ · ମୋବାଇଲ…',
      matchingPrefix: 'ମେଳ ହେଉଛି',
      countSuffix: 'ସଦସ୍ୟ',
      noMembersTitle: 'କୌଣସି ସଦସ୍ୟ ମିଳିଲେ ନାହିଁ',
      noMembersSubtitle: 'ଅନ୍ୟ ସନ୍ଧାନ ବା ଫିଲ୍ଟର ଚେଷ୍ଟା କରନ୍ତୁ',
      allLoadedPrefix: 'ସମସ୍ତ', allLoadedSuffix: 'ସଦସ୍ୟ ଲୋଡ୍ ହେଲେ',
      maleHof: '♂ ପୁରୁଷ ମୁଖ୍ୟ', femaleHof: '♀ ମହିଳା ମୁଖ୍ୟ',
      // Filter modal
      filterModalTitle: 'ସଦସ୍ୟ ଫିଲ୍ଟର୍ କରନ୍ତୁ',
      districtSectionTitle: 'ଜିଲ୍ଲା', talukaSectionTitle: 'ତାଲୁକ',
      panchayatSectionTitle: 'ପଞ୍ଚାୟତ', villageSectionTitle: 'ଗ୍ରାମ',
      genderSectionTitle: 'ପରିବାର ମୁଖ୍ୟଙ୍କ ଲିଙ୍ଗ',
      allDistricts: 'ସମସ୍ତ ଜିଲ୍ଲା',
      allTalukasInPrefix: 'ସମସ୍ତ ତାଲୁକ', allPanchayatsInPrefix: 'ସମସ୍ତ ପଞ୍ଚାୟତ', allVillagesInPrefix: 'ସମସ୍ତ ଗ୍ରାମ',
      allGenders: 'ସମସ୍ତ ଲିଙ୍ଗ', maleHead: '♂ ପୁରୁଷ ମୁଖ୍ୟ', femaleHead: '♀ ମହିଳା ମୁଖ୍ୟ',
      resetButton: 'ପୁନଃସେଟ୍',
      showResultsPrefix: 'ଦେଖନ୍ତୁ', showResultsSuffix: 'ଫଳାଫଳ',
      // Member card
      activeBadge: 'ସକ୍ରିୟ',
      headGenderTitle: 'ମୁଖ୍ୟଙ୍କ ଲିଙ୍ଗ',
      genderFemaleTag: '♀ ମହିଳା', genderMaleTag: '♂ ପୁରୁଷ',
      maleWord: 'ପୁରୁଷ', femaleWord: 'ମହିଳା',
      familyMembersListLabel: 'ପାରିବାରିକ ସଦସ୍ୟ ତାଲିକା',
    },
    memberProfile: {
      notFoundText: 'ପ୍ରୋଫାଇଲ୍ ମିଳିଲା ନାହିଁ କିମ୍ବା ପ୍ରତିବନ୍ଧିତ।',
      returnToMembers: '← ସଦସ୍ୟ ତାଲିକାକୁ ଫେରନ୍ତୁ',
      backLabel: '← ପଛକୁ',
      followingLabel: 'ଅନୁସରଣ କରୁଛନ୍ତି', followLabel: 'ଅନୁସରଣ କରନ୍ତୁ', messageLabel: 'ବାର୍ତ୍ତା',
      headOfFamily: 'ପରିବାର ମୁଖ୍ୟ',
      joinedPrefix: 'ଯୋଗ ଦେଲେ',
      postsTabLabel: 'ପୋଷ୍ଟ', familyTabLabel: 'ପରିବାର', galleryTabLabel: 'ଗ୍ୟାଲେରୀ',
      statsFollowersLabel: 'ଅନୁସରଣକାରୀ',
      familyMembersHeader: 'ପାରିବାରିକ ସଦସ୍ୟ',
      noPostsTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପୋଷ୍ଟ ନାହିଁ', noPostsSubtitle: 'ଏହି ସଦସ୍ୟ ଏପର୍ଯ୍ୟନ୍ତ ପୋଷ୍ଟ କରିନାହାଁନ୍ତି',
      noPhotosTitle: 'କୌଣସି ଫଟୋ ନାହିଁ', noPhotosSubtitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଟୋ ସେୟାର ହୋଇନାହିଁ',
    },
    profile: {
      title: 'ମୋର ପ୍ରୋଫାଇଲ୍',
      settingsButton: 'ସେଟିଂ',
      memberBadge: 'ପଣ୍ଡାର ସଦସ୍ୟ',
      headOfFamily: 'ପରିବାର ମୁଖ୍ୟ',
      mobilePrefix: 'ମୋବାଇଲ:',
      familyHubHeader: 'ପାରିବାରିକ କେନ୍ଦ୍ର',
      familyTreeLabel: 'ପାରିବାରିକ ବଂଶାବଳୀ', familyTreeDesc: 'ବଂଶାବଳୀ ବୃକ୍ଷ',
      matrimonyLabel: 'ବିବାହ', matrimonyDesc: 'ମେଳ ଖୋଜନ୍ତୁ',
      familyAlbumsLabel: 'ପାରିବାରିକ ଆଲବମ୍', familyAlbumsDesc: 'ସେୟାର ହୋଇଥିବା ଗ୍ୟାଲେରୀ',
      familyEventsLabel: 'ପାରିବାରିକ କାର୍ଯ୍ୟକ୍ରମ', familyEventsDesc: 'RSVP ହୋଇଥିବା କାର୍ଯ୍ୟକ୍ରମ',
      leadersLabel: 'ନେତୃତ୍ୱ', leadersDesc: 'ସାମୁଦାୟିକ ନେତୃତ୍ୱ',
      addressInfoHeader: 'ଠିକଣା ସୂଚନା',
      villageLabel: 'ଗ୍ରାମ', panchayatLabel: 'ପଞ୍ଚାୟତ', fullAddressLabel: 'ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା',
      notSpecified: 'ଉଲ୍ଲେଖ ହୋଇନାହିଁ',
      villagePlaceholder: 'ଗ୍ରାମ ନାମ', panchayatPlaceholder: 'ପଞ୍ଚାୟତ ନାମ', addressPlaceholder: 'ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା ବିବରଣୀ',
      familyMembersHeader: 'ପାରିବାରିକ ସଦସ୍ୟ',
      noFamilyMembers: 'କୌଣସି ପାରିବାରିକ ସଦସ୍ୟ ପଞ୍ଜିକୃତ ହୋଇନାହାଁନ୍ତି।',
      yrsAbbrev: 'ବର୍ଷ',
      profilePhotoTitle: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ', profilePhotoMessage: 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଫଟୋ ବଦଳାନ୍ତୁ କିମ୍ବା ହଟାନ୍ତୁ।',
      removePhoto: 'ଫଟୋ ହଟାନ୍ତୁ', removedTitle: 'ହଟାଗଲା', removedMessage: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ ହଟାଗଲା।',
      uploadNewPhoto: 'ଗ୍ୟାଲେରୀରୁ ବାଛନ୍ତୁ', uploadTitle: 'ଅପଲୋଡ୍', uploadMessage: 'ଫଟୋ ଅପଲୋଡ୍ ସିମୁଲେଟ୍ ହେଲା।',
      takePhoto: 'ଫଟୋ ଉଠାନ୍ତୁ', cameraPermissionDenied: 'ଫଟୋ ଉଠାଇବାକୁ କ୍ୟାମେରା ଅନୁମତି ଆବଶ୍ୟକ।',
      galleryPermissionDenied: 'ଫଟୋ ବାଛିବାକୁ ଗ୍ୟାଲେରୀ ଅନୁମତି ଆବଶ୍ୟକ।',
      uploadError: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ ଅପଡେଟ୍ କରିବାରେ ବିଫଳ।',
      profileSavedTitle: 'ପ୍ରୋଫାଇଲ୍ ସେଭ୍ ହେଲା', profileSavedMessage: 'ଆପଣଙ୍କ ଠିକଣା ବିବରଣୀ ଅପଡେଟ୍ ହୋଇଛି।',
    },
    familyTree: {
      title: 'ପାରିବାରିକ ବଂଶ ବୃକ୍ଷ',
      subtitle: 'ଆପଣଙ୍କ ପରିବାର, ଏକ ନଜରରେ',
      headOfFamily: 'ପରିବାର ମୁଖ୍ୟ',
      membershipPrefix: 'ସଦସ୍ୟତା #',
      groupSpouse: 'ପତି/ପତ୍ନୀ',
      groupParents: 'ପିତାମାତା',
      groupChildren: 'ସନ୍ତାନ',
      groupOthers: 'ଅନ୍ୟ ପାରିବାରିକ ସଦସ୍ୟ',
      ageSuffix: 'ବର୍ଷ',
      emptyTitle: 'କୌଣସି ପାରିବାରିକ ତଥ୍ୟ ନାହିଁ',
      emptySubtitle: 'ଆପଣଙ୍କ ପାରିବାରିକ ବିବରଣୀ ଏପର୍ଯ୍ୟନ୍ତ ପ୍ରୋଫାଇଲ୍‌ରେ ଯୋଡ଼ାଯାଇ ନାହିଁ।',
    },
    familyAlbums: {
      title: 'ପାରିବାରିକ ଆଲବମ',
      subtitle: 'ଆପଣଙ୍କ ପରିବାର ମଧ୍ୟରେ ସେୟାର ହୋଇଥିବା ଫଟୋ',
      loadError: 'ପାରିବାରିକ ଆଲବମ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      createAlbum: 'ଆଲବମ ତିଆରି କରନ୍ତୁ',
      newAlbumTitle: 'ନୂଆ ଆଲବମ',
      albumTitleLabel: 'ଶୀର୍ଷକ',
      albumTitlePlaceholder: 'ଯଥା ଦୀପାବଳି ୨୦୨୫',
      albumDescriptionLabel: 'ବିବରଣୀ',
      albumDescriptionPlaceholder: 'ଏକ ସଂକ୍ଷିପ୍ତ ବିବରଣୀ ଯୋଡ଼ନ୍ତୁ (ଇଚ୍ଛାଧୀନ)',
      coverPhotoLabel: 'କଭର ଫଟୋ (ଇଚ୍ଛାଧୀନ)',
      chooseCoverPhoto: 'କଭର ଫଟୋ ବାଛନ୍ତୁ',
      changeCoverPhoto: 'କଭର ଫଟୋ ବଦଳାନ୍ତୁ',
      createButton: 'ଆଲବମ ତିଆରି କରନ୍ତୁ',
      creatingButton: 'ତିଆରି ହେଉଛି…',
      titleRequiredError: 'ଦୟାକରି ଏକ ଆଲବମ ଶୀର୍ଷକ ପ୍ରବେଶ କରନ୍ତୁ।',
      createError: 'ଆଲବମ ତିଆରି କରିବାରେ ବିଫଳ।',
      createSuccessTitle: 'ଆଲବମ ତିଆରି ହେଲା',
      createSuccessMessage: 'ଆପଣଙ୍କ ନୂଆ ପାରିବାରିକ ଆଲବମ ପ୍ରସ୍ତୁତ ଅଛି।',
      photosCountSuffix: 'ଫଟୋ',
      photoCountSingular: 'ଫଟୋ',
      emptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆଲବମ ନାହିଁ',
      emptySubtitle: 'ଫଟୋ ସେୟାର କରିବା ଆରମ୍ଭ କରିବାକୁ ଆପଣଙ୍କ ପ୍ରଥମ ଆଲବମ ତିଆରି କରନ୍ତୁ।',
      deleteAlbumConfirmTitle: 'ଆଲବମ ଡିଲିଟ୍ କରନ୍ତୁ',
      deleteAlbumConfirmMessage: 'ଏହା ଏହି ଆଲବମ ଏବଂ ଏଥିରେ ଥିବା ସମସ୍ତ ଫଟୋକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିଦେବ। ଜାରି ରଖିବେ କି?',
      deleteError: 'ଆଲବମ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ।',
      deleteSuccessMessage: 'ଆଲବମ ଡିଲିଟ୍ ହୋଇଗଲା।',
      addPhotos: 'ଫଟୋ ଯୋଡ଼ନ୍ତୁ',
      addingPhotos: 'ଅପଲୋଡ୍ ହେଉଛି…',
      addPhotosError: 'ଫଟୋ ଯୋଡ଼ିବାରେ ବିଫଳ।',
      addPhotosSuccessMessage: 'ଫଟୋ ଆଲବମ୍‌ରେ ଯୋଡ଼ାଗଲା।',
      noPhotosInAlbum: 'ଏହି ଆଲବମ୍‌ରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଟୋ ନାହିଁ।',
      cancelButton: 'ବାତିଲ',
      closeButton: 'ବନ୍ଦ କରନ୍ତୁ',
    },
    familyEvents: {
      title: 'ପାରିବାରିକ ଅନୁଷ୍ଠାନ',
      subtitle: 'ଆପଣଙ୍କ ନିଜ ପରିବାର ପାଇଁ ଅନୁଷ୍ଠାନ',
      loadError: 'ପାରିବାରିକ ଅନୁଷ୍ଠାନ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      createEvent: 'ଅନୁଷ୍ଠାନ ତିଆରି କରନ୍ତୁ',
      newEventTitle: 'ନୂଆ ପାରିବାରିକ ଅନୁଷ୍ଠାନ',
      eventTitleLabel: 'ଶୀର୍ଷକ',
      eventTitlePlaceholder: 'ଯଥା ଜେଜେମାଙ୍କ ଜନ୍ମଦିନ',
      descriptionLabel: 'ବିବରଣୀ',
      descriptionPlaceholder: 'ବିବରଣୀ ଯୋଡ଼ନ୍ତୁ (ଇଚ୍ଛାଧୀନ)',
      dateLabel: 'ତାରିଖ',
      datePlaceholder: 'YYYY-MM-DD',
      locationLabel: 'ସ୍ଥାନ',
      locationPlaceholder: 'ଏହା କେଉଁଠାରେ ହେବ?',
      typeLabel: 'ପ୍ରକାର',
      typePlaceholder: 'ଯଥା ଜନ୍ମଦିନ, ବାର୍ଷିକୀ, ସମାବେଶ',
      createButton: 'ଅନୁଷ୍ଠାନ ତିଆରି କରନ୍ତୁ',
      creatingButton: 'ତିଆରି ହେଉଛି…',
      titleRequiredError: 'ଦୟାକରି ଏକ ଅନୁଷ୍ଠାନ ଶୀର୍ଷକ ପ୍ରବେଶ କରନ୍ତୁ।',
      dateRequiredError: 'ଦୟାକରି ଏକ ବୈଧ ତାରିଖ (YYYY-MM-DD) ପ୍ରବେଶ କରନ୍ତୁ।',
      createError: 'ଅନୁଷ୍ଠାନ ତିଆରି କରିବାରେ ବିଫଳ।',
      createSuccessTitle: 'ଅନୁଷ୍ଠାନ ତିଆରି ହେଲା',
      createSuccessMessage: 'ଆପଣଙ୍କ ପାରିବାରିକ ଅନୁଷ୍ଠାନ ଯୋଡ଼ାଗଲା।',
      emptyTitle: 'କୌଣସି ପାରିବାରିକ ଅନୁଷ୍ଠାନ ନାହିଁ',
      emptySubtitle: 'ଆପଣଙ୍କ ପରିବାର ସହ ଯୋଜନା ଆରମ୍ଭ କରିବାକୁ ଏକ ଅନୁଷ୍ଠାନ ତିଆରି କରନ୍ତୁ।',
      deleteEventConfirmTitle: 'ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ କରନ୍ତୁ',
      deleteEventConfirmMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଏହି ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      deleteError: 'ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ।',
      deleteSuccessMessage: 'ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ ହୋଇଗଲା।',
      tabUpcoming: 'ଆଗାମୀ',
      tabPast: 'ପୂର୍ବ',
      rsvpGoing: 'ଯିବି',
      rsvpMaybe: 'ହୁଏତ',
      rsvpNotGoing: 'ଯିବି ନାହିଁ',
      rsvpError: 'RSVP ଦାଖଲ କରିବାରେ ବିଫଳ।',
      locationTBA: 'ପରେ ଜଣାଇବେ',
      cancelButton: 'ବାତିଲ',
    },
    explore: {
      title: 'ଅନ୍ୱେଷଣ',
      tabTrending: 'ଟ୍ରେଣ୍ଡିଂ', tabMembers: 'ସଦସ୍ୟ', tabHashtags: 'ହ୍ୟାସ୍‌ଟାଗ୍',
      trendingPostsTitle: 'ଟ୍ରେଣ୍ଡିଂ ପୋଷ୍ଟ',
      trendingPostsSubtitle: 'ସମାଜରେ ସର୍ବାଧିକ ଆଲୋଚିତ ପୋଷ୍ଟ। (ଶୀଘ୍ର ଆସୁଛି)',
      activeMembersLabel: 'ଆଜି ସକ୍ରିୟ ମୋଟ ସଦସ୍ୟ',
      noPopularMembers: 'କୌଣସି ଲୋକପ୍ରିୟ ସଦସ୍ୟ ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ।',
      noTags: 'ବର୍ତ୍ତମାନ କୌଣସି ଟ୍ୟାଗ୍ ଉପଲବ୍ଧ ନାହିଁ।',
    },
    feedComponents: {
      warningTitle: 'ଚେତାବନୀ',
      inappropriateCommentMessage: 'ଆପଣଙ୍କ ମନ୍ତବ୍ୟରେ ଅନୁପଯୁକ୍ତ ବିଷୟବସ୍ତୁ ଅଛି।',
      cancelButtonLabel: 'ବାତିଲ',
      saveButtonLabel: 'ସେଭ୍',
      deleteButtonLabel: 'ଡିଲିଟ୍',
      commentWord: 'ମନ୍ତବ୍ୟ',
      commentsWordPlural: 'ମନ୍ତବ୍ୟ',
      likeLabel: 'ଲାଇକ୍',
      likedLabel: 'ଲାଇକ୍ ହୋଇଛି',
      replyLabel: 'ଉତ୍ତର',
      writeReplyPlaceholder: 'ଉତ୍ତର ଲେଖନ୍ତୁ...',
      noCommentsYetText: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମନ୍ତବ୍ୟ ନାହିଁ',
      loadMoreCommentsLabel: 'ଅଧିକ ମନ୍ତବ୍ୟ ଲୋଡ୍ କରନ୍ତୁ',
      writeCommentPlaceholder: 'ମନ୍ତବ୍ୟ ଲେଖନ୍ତୁ...',
      editPostLabel: 'ପୋଷ୍ଟ ଏଡିଟ୍ କରନ୍ତୁ',
      deletePostLabel: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ',
      savePostLabel: 'ପୋଷ୍ଟ ସେଭ୍ କରନ୍ତୁ',
      unsavePostLabel: 'ପୋଷ୍ଟ ଅନ୍‌ସେଭ୍ କରନ୍ତୁ',
      reportPostLabel: 'ପୋଷ୍ଟ ରିପୋର୍ଟ କରନ୍ତୁ',
      deletePostConfirmTitle: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ',
      deletePostConfirmMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଏହି ପୋଷ୍ଟ ଡିଲିଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      reportPostModalTitle: 'ପୋଷ୍ଟ ରିପୋର୍ଟ କରନ୍ତୁ',
      reportPostPrompt: 'ଆପଣ ଏହି ପୋଷ୍ଟକୁ କାହିଁକି ରିପୋର୍ଟ କରୁଛନ୍ତି?',
      submitReportLabel: 'ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ',
      reportReasonAdult: 'ବୟସ୍କ / ଯୌନ ବିଷୟବସ୍ତୁ',
      reportReasonHarassment: 'ହଇରାଣ ବା ଧମକ',
      reportReasonHateSpeech: 'ଘୃଣା ବକ୍ତବ୍ୟ',
      reportReasonSpam: 'ସ୍ପାମ୍ କିମ୍ବା ଭ୍ରାନ୍ତିଜନକ',
      reportReasonViolence: 'ହିଂସା କିମ୍ବା ବିପଦଜନକ ବିଷୟବସ୍ତୁ',
      reportReasonFalseInfo: 'ଭୁଲ ସୂଚନା',
      reportReasonOther: 'ଅନ୍ୟାନ୍ୟ',
      sharePostTitlePrefix: 'ପୋଷ୍ଟ କରିଛନ୍ତି',
      genericErrorTitle: 'ତ୍ରୁଟି',
      postValidationErrorMessage: 'ଦୟାକରି କିଛି ଟେକ୍ସଟ୍ କିମ୍ବା ମିଡିଆ/ପୋଲ୍ ଯୋଡ଼ନ୍ତୁ।',
      inappropriateContentTitle: 'ଅନୁପଯୁକ୍ତ ବିଷୟବସ୍ତୁ',
      inappropriateContentMessage: 'ଆପଣଙ୍କ ପୋଷ୍ଟରେ ପ୍ରତିବନ୍ଧିତ ଶବ୍ଦ ଅଛି।',
      shareSomethingPlaceholder: 'ସମାଜ ସହ କିଛି ସେୟାର କରନ୍ତୁ...',
      createPostTitle: 'ପୋଷ୍ଟ ତିଆରି କରନ୍ତୁ',
      postButtonLabel: 'ପୋଷ୍ଟ',
      postingToMemberPortal: 'ସଦସ୍ୟ ପୋର୍ଟାଲକୁ ପୋଷ୍ଟ କରୁଛନ୍ତି',
      whatsOnYourMindPlaceholder: 'ଆପଣଙ୍କ ମନରେ କଣ ଅଛି? (#ଟ୍ୟାଗ୍ କିମ୍ବା @ମେନ୍‌ସନ୍ ବ୍ୟବହାର କରନ୍ତୁ)',
      enterLocationPlaceholder: 'ସ୍ଥାନ ଟ୍ୟାଗ୍ ପ୍ରବେଶ କରନ୍ତୁ...',
      createPollTitle: 'ପୋଲ୍ ତିଆରି କରନ୍ତୁ',
      pollLimitReachedTitle: 'ସୀମା ପହଞ୍ଚିଲା',
      pollLimitReachedMessage: 'ଆପଣ ସର୍ବାଧିକ ୫ଟି ବିକଳ୍ପ ଯୋଡ଼ି ପାରିବେ।',
      pollMinOptionsTitle: 'ଆବଶ୍ୟକ',
      pollMinOptionsMessage: 'ଏକ ପୋଲ୍ ପାଇଁ ଅତିକମରେ ୨ଟି ବିକଳ୍ପ ଆବଶ୍ୟକ।',
      pollQuestionRequiredMessage: 'ଦୟାକରି ଏକ ପୋଲ୍ ପ୍ରଶ୍ନ ପ୍ରବେଶ କରନ୍ତୁ।',
      pollOptionsRequiredMessage: 'ଦୟାକରି ଅତିକମରେ ୨ଟି ବୈଧ ବିକଳ୍ପ ପ୍ରବେଶ କରନ୍ତୁ।',
      pollQuestionLabel: 'ପ୍ରଶ୍ନ',
      pollQuestionPlaceholder: 'ଆପଣ କଣ ପଚାରିବାକୁ ଚାହୁଁଛନ୍ତି?',
      pollOptionsLabel: 'ବିକଳ୍ପ',
      pollOptionPlaceholderPrefix: 'ବିକଳ୍ପ',
      addOptionLabel: 'ବିକଳ୍ପ ଯୋଡ଼ନ୍ତୁ',
      createButtonLabel: 'ତିଆରି କରନ୍ତୁ',
      voteWord: 'ଭୋଟ୍',
      votesWordPlural: 'ଭୋଟ୍',
      pollEndsPrefix: 'ସମାପ୍ତ',
      addStoryLabel: 'ଷ୍ଟୋରୀ ଯୋଡ଼ନ୍ତୁ',
    },
    admin: {
      entryLinkLabel: 'ଆଡମିନ ଲଗଇନ',
      loginTitle: 'ଆଡମିନ ଲଗଇନ',
      loginSubtitle: 'କେବଳ କର୍ମଚାରୀଙ୍କ ପାଇଁ',
      usernameLabel: 'ୟୁଜରନେମ',
      usernamePlaceholder: 'ୟୁଜରନେମ ପ୍ରବେଶ କରନ୍ତୁ',
      passwordLabel: 'ପାସୱାର୍ଡ',
      passwordPlaceholder: 'ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ',
      loginButton: 'ଲଗଇନ କରନ୍ତୁ',
      usernameRequiredError: 'ଦୟାକରି ଆପଣଙ୍କର ୟୁଜରନେମ ପ୍ରବେଶ କରନ୍ତୁ',
      passwordRequiredError: 'ଦୟାକରି ଆପଣଙ୍କର ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ',
      loginError: 'ଅବୈଧ ୟୁଜରନେମ କିମ୍ବା ପାସୱାର୍ଡ',

      dashboardTitle: 'ଆଡମିନ ଡ୍ୟାସବୋର୍ଡ',
      roleAdmin: 'ଆଡମିନ',
      roleSuperadmin: 'ସୁପର ଆଡମିନ',
      membersCardTitle: 'ସଦସ୍ୟ',
      membersCardDesc: 'ସଦସ୍ୟ ଖାତା ଦେଖନ୍ତୁ, ଖୋଜନ୍ତୁ ଓ ପରିଚାଳନା କରନ୍ତୁ',
      reportsCardTitle: 'ରିପୋର୍ଟ ହୋଇଥିବା ପୋଷ୍ଟ',
      reportsCardDesc: 'ଚିହ୍ନଟ ହୋଇଥିବା ବିଷୟବସ୍ତୁ ସମୀକ୍ଷା କରନ୍ତୁ',
      usersCardTitle: 'ଆଡମିନ ପରିଚାଳନା',
      usersCardDesc: 'ଆଡମିନ ଖାତା ତିଆରି ଓ ହଟାନ୍ତୁ',
      logoutButton: 'ଆଡମିନରୁ ଲଗ୍ ଆଉଟ୍ କରନ୍ତୁ',
      confirmLogoutTitle: 'ଲଗ୍ ଆଉଟ୍',
      confirmLogoutMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଆଡମିନ ପେନେଲରୁ ଲଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',

      membersTitle: 'ସଦସ୍ୟ',
      membersSearchPlaceholder: 'ନାମ, ସଦସ୍ୟତା ନମ୍ବର, ଗ୍ରାମ ଦ୍ୱାରା ଖୋଜନ୍ତୁ…',
      membersLoadError: 'ସଦସ୍ୟ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      membersEmptyTitle: 'କୌଣସି ସଦସ୍ୟ ମିଳିଲେ ନାହିଁ',
      membersEmptySubtitle: 'ଅନ୍ୟ ଏକ ସନ୍ଧାନ ଶବ୍ଦ ଚେଷ୍ଟା କରନ୍ତୁ',
      bannedBadge: 'ପ୍ରତିବନ୍ଧିତ',
      activeBadge: 'ସକ୍ରିୟ',
      banButton: 'ସଦସ୍ୟଙ୍କୁ ପ୍ରତିବନ୍ଧ କରନ୍ତୁ',
      unbanButton: 'ପ୍ରତିବନ୍ଧ ହଟାନ୍ତୁ',
      confirmBanTitle: 'ସଦସ୍ୟଙ୍କୁ ପ୍ରତିବନ୍ଧ କରନ୍ତୁ',
      confirmBanMessage: 'ଏହି ସଦସ୍ୟ ଆପ୍‌ରୁ ପ୍ରତିବନ୍ଧିତ ହେବେ ଏବଂ ସେମାନଙ୍କ ବିଷୟବସ୍ତୁ ଲୁଚିତ ରହିବ। ଜାରି ରଖିବେ କି?',
      confirmUnbanTitle: 'ପ୍ରତିବନ୍ଧ ହଟାନ୍ତୁ',
      confirmUnbanMessage: 'ଏହି ସଦସ୍ୟଙ୍କ ଆପ୍ ପ୍ରବେଶ ପୁନଃସ୍ଥାପନ କରିବେ କି?',
      banError: 'ସଦସ୍ୟ ସ୍ଥିତି ଅପଡେଟ୍ କରିବାରେ ବିଫଳ',

      memberDetailTitle: 'ସଦସ୍ୟ ବିବରଣୀ',
      postsCountLabel: 'ପୋଷ୍ଟ',
      reportsAgainstLabel: 'ବିରୁଦ୍ଧରେ ରିପୋର୍ଟ',
      reportsFiledLabel: 'ଦାଖଲ ହୋଇଥିବା ରିପୋର୍ଟ',
      memberLoadError: 'ସଦସ୍ୟ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      memberNotFound: 'ସଦସ୍ୟ ମିଳିଲେ ନାହିଁ',

      editMemberTitle: 'ସଦସ୍ୟ ସମ୍ପାଦନ କରନ୍ତୁ',
      memberEditSaveError: 'ସଦସ୍ୟ ସେଭ୍ କରିବାରେ ବିଫଳ',
      memberEditMobileLabel: 'ମୋବାଇଲ',
      memberEditDistrictLabel: 'ଜିଲ୍ଲା',
      memberEditTalukaLabel: 'ତହସିଲ',
      memberEditPanchayatLabel: 'ପଞ୍ଚାୟତ',
      memberEditVillageLabel: 'ଗ୍ରାମ',

      reportsTitle: 'ରିପୋର୍ଟ ହୋଇଥିବା ପୋଷ୍ଟ',
      reportsLoadError: 'ରିପୋର୍ଟ ହୋଇଥିବା ପୋଷ୍ଟ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      reportsEmptyTitle: 'ସବୁ ଠିକ୍ ଅଛି',
      reportsEmptySubtitle: 'ସମୀକ୍ଷା ପାଇଁ କୌଣସି ପୋଷ୍ଟ ବାକି ନାହିଁ',
      reasonLabel: 'କାରଣ',
      approveButton: 'ଅନୁମୋଦନ',
      rejectButton: 'ପ୍ରତ୍ୟାଖ୍ୟାନ',
      confirmRejectTitle: 'ପୋଷ୍ଟ ପ୍ରତ୍ୟାଖ୍ୟାନ କରନ୍ତୁ',
      confirmRejectMessage: 'ଏହା ପୋଷ୍ଟକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିଦେବ। ଏହା ପୂର୍ବବତ୍ ହୋଇପାରିବ ନାହିଁ। ଜାରି ରଖିବେ କି?',
      moderationActionError: 'ଏହି ପୋଷ୍ଟ ଅପଡେଟ୍ କରିବାରେ ବିଫଳ',

      usersTitle: 'ଆଡମିନ ପରିଚାଳନା',
      usersLoadError: 'ଆଡମିନ ଖାତା ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      usersEmptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆଡମିନ ଖାତା ନାହିଁ',
      newAdminTitle: 'ନୂଆ ଆଡମିନ ଖାତା',
      roleFieldLabel: 'ଭୂମିକା',
      createButton: 'ତିଆରି କରନ୍ତୁ',
      createAdminError: 'ଆଡମିନ ଖାତା ତିଆରି କରିବାରେ ବିଫଳ',
      usernameRequiredCreateError: 'ଦୟାକରି ଏକ ୟୁଜରନେମ ପ୍ରବେଶ କରନ୍ତୁ',
      passwordRequiredCreateError: 'ଦୟାକରି ଏକ ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ',
      removeButton: 'ହଟାନ୍ତୁ',
      confirmRemoveTitle: 'ଆଡମିନ ହଟାନ୍ତୁ',
      confirmRemoveMessage: 'ଏହି ଆଡମିନ ଖାତା ହଟାଇବେ କି? ସେମାନେ ଆଉ ଲଗଇନ କରିପାରିବେ ନାହିଁ।',
      removeError: 'ଆଡମିନ ଖାତା ହଟାଇବାରେ ବିଫଳ',
      lastLoginLabel: 'ଶେଷ ଲଗଇନ',
      neverLabel: 'କେବେ ନୁହେଁ',

      editAdminTitle: 'ଆଡମିନ ଖାତା ସମ୍ପାଦନ କରନ୍ତୁ',
      editAdminError: 'ଆଡମିନ ଖାତା ଅପଡେଟ୍ କରିବାରେ ବିଫଳ',
      newPasswordOptionalLabel: 'ନୂଆ ପାସୱାର୍ଡ (ବୈକଳ୍ପିକ)',
      newPasswordOptionalPlaceholder: 'ପୁରୁଣା ପାସୱାର୍ଡ ରଖିବାକୁ ଖାଲି ଛାଡ଼ନ୍ତୁ',
      confirmBanAdminTitle: 'ଆଡମିନ ଖାତା ନିଷ୍କ୍ରିୟ କରନ୍ତୁ',
      confirmBanAdminMessage: 'ଏହି ଆଡମିନ ଆଉ ଲଗଇନ କରିପାରିବେ ନାହିଁ। ଜାରି ରଖିବେ କି?',
      confirmUnbanAdminTitle: 'ଆଡମିନ ଖାତା ସକ୍ରିୟ କରନ୍ତୁ',
      confirmUnbanAdminMessage: 'ଏହି ଆଡମିନଙ୍କ ଲଗଇନ କ୍ଷମତା ପୁନଃସ୍ଥାପନ କରିବେ କି?',
      adminStatusError: 'ଆଡମିନ ଖାତା ସ୍ଥିତି ଅପଡେଟ୍ କରିବାରେ ବିଫଳ',

      trackerCardTitle: 'କାର୍ଯ୍ୟକଳାପ ଟ୍ରାକର୍',
      trackerCardDesc: 'ସଦସ୍ୟ ଓ ଆଡମିନଙ୍କ କାର୍ଯ୍ୟକଳାପର ଅଡିଟ୍ ଟ୍ରେଲ୍',
      matrimonyCardTitle: 'ବିବାହ',
      matrimonyCardDesc: 'ବିବାହ ପ୍ରାର୍ଥୀ ପ୍ରୋଫାଇଲ ପରିଚାଳନା କରନ୍ତୁ',
      postsCardTitle: 'ଫିଡ୍ ପୋଷ୍ଟ',
      postsCardDesc: 'ସମସ୍ତ ସାମୁଦାୟିକ ଫିଡ୍ ପୋଷ୍ଟ ମଡରେଟ୍ କରନ୍ତୁ',
      announcementsCardTitle: 'ଘୋଷଣା',
      announcementsCardDesc: 'ସରକାରୀ ଘୋଷଣା ତିଆରି ଓ ପରିଚାଳନା କରନ୍ତୁ',
      expensesCardTitle: 'ଖର୍ଚ୍ଚ',
      expensesCardDesc: 'ସାମୁଦାୟିକ ଆୟ ଓ ଖର୍ଚ୍ଚ ଟ୍ରାକ୍ କରନ୍ତୁ',
      settingsCardTitle: 'ସେଟିଂ',
      settingsCardDesc: 'ଆପଣଙ୍କ ଆଡମିନ ପାସୱାର୍ଡ ବଦଳାନ୍ତୁ',
      leadersCardTitle: 'ନେତୃତ୍ୱ',
      leadersCardDesc: 'ସାମୁଦାୟିକ ନେତାଙ୍କ ପ୍ରୋଫାଇଲ ପରିଚାଳନା କରନ୍ତୁ',

      leadersTitle: 'ନେତୃତ୍ୱ ପରିଚାଳନା',
      leadersSearchPlaceholder: 'ନାମ କିମ୍ବା ଭୂମିକା ଦ୍ୱାରା ଖୋଜନ୍ତୁ…',
      leadersLoadError: 'ନେତାମାନଙ୍କୁ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      leadersEmptyTitle: 'କୌଣସି ନେତା ମିଳିଲେ ନାହିଁ',
      leadersEmptySubtitle: 'ପ୍ରଥମ ନେତା ଯୋଡିବାକୁ + ଦବାନ୍ତୁ',
      leaderCreateTitle: 'ନୂତନ ନେତା',
      leaderEditTitle: 'ନେତା ସମ୍ପାଦନ କରନ୍ତୁ',
      leaderNameLabel: 'ନାମ',
      leaderNameOrLabel: 'ନାମ (ଓଡ଼ିଆ)',
      leaderRoleLabel: 'ଭୂମିକା',
      leaderRoleOrLabel: 'ଭୂମିକା (ଓଡ଼ିଆ)',
      leaderLevelLabel: 'ସ୍ତର',
      leaderLocationLabel: 'ସ୍ଥାନ',
      leaderLocationPlaceholder: 'ଉଦାହରଣ: ଜିଲ୍ଲା, ବ୍ଲକ୍ କିମ୍ବା ଗ୍ରାମର ନାମ',
      leaderDisplayOrderLabel: 'ପ୍ରଦର୍ଶନ କ୍ରମ',
      leaderDisplayOrderPlaceholder: 'ଉଦାହରଣ: 1',
      leaderNameRequiredError: 'ଦୟାକରି ଏକ ନାମ ପ୍ରବେଶ କରନ୍ତୁ',
      leaderRoleRequiredError: 'ଦୟାକରି ଏକ ଭୂମିକା ପ୍ରବେଶ କରନ୍ତୁ',
      leaderSaveError: 'ନେତା ସେଭ୍ କରିବାରେ ବିଫଳ',
      leaderDeleteError: 'ନେତା ଡିଲିଟ୍ କରିବାରେ ବିଫଳ',
      confirmDeleteLeaderTitle: 'ନେତା ଡିଲିଟ୍ କରନ୍ତୁ',
      confirmDeleteLeaderMessage: 'ଏହା ଏହି ନେତା ପ୍ରୋଫାଇଲକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିବ। ଜାରି ରଖିବେ କି?',

      trackerTitle: 'କାର୍ଯ୍ୟକଳାପ ଟ୍ରାକର୍',
      trackerTargetLabel: 'ଲକ୍ଷ୍ୟ',
      trackerIpLabel: 'IP ଠିକଣା',
      trackerDeviceLabel: 'ଡିଭାଇସ୍',
      trackerFilterAll: 'ସମସ୍ତ',
      trackerFilterMembers: 'ସଦସ୍ୟ',
      trackerFilterAdmins: 'ଆଡମିନ',
      trackerMigrationPendingTitle: 'କାର୍ଯ୍ୟକଳାପ ଟ୍ରାକିଂ ଏପର୍ଯ୍ୟନ୍ତ ସକ୍ରିୟ ହୋଇନାହିଁ',
      trackerMigrationPendingSubtitle: 'ଏକ ବକେୟା ଅପଡେଟ୍ ପ୍ରୟୋଗ ହେଲାପରେ କାର୍ଯ୍ୟକଳାପ ଟ୍ରାକିଂ ଆରମ୍ଭ ହେବ',
      trackerEmptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଯ୍ୟକଳାପ ନାହିଁ',
      trackerEmptySubtitle: 'କାର୍ଯ୍ୟଗୁଡ଼ିକ ଘଟିବା ମାତ୍ରେ ଏଠାରେ ଦେଖାଯିବ',
      action_admin_created: 'ଆଡମିନ ଖାତା ତିଆରି ହେଲା',
      action_admin_deleted: 'ଆଡମିନ ଖାତା ହଟାଗଲା',
      action_admin_login: 'ଆଡମିନ ଲଗଇନ ହେଲେ',
      action_admin_banned: 'ଆଡମିନ ଖାତା ନିଷ୍କ୍ରିୟ ହେଲା',
      action_admin_unbanned: 'ଆଡମିନ ଖାତା ସକ୍ରିୟ ହେଲା',
      action_announcement_created: 'ଘୋଷଣା ତିଆରି ହେଲା',
      action_announcement_deleted: 'ଘୋଷଣା ଡିଲିଟ୍ ହେଲା',
      action_announcement_updated: 'ଘୋଷଣା ଅପଡେଟ୍ ହେଲା',
      action_comment_created: 'ମନ୍ତବ୍ୟ ଦିଆଗଲା',
      action_expense_created: 'ଖର୍ଚ୍ଚ ପ୍ରବିଷ୍ଟି ଯୋଡ଼ାଗଲା',
      action_follow_toggled: 'ଅନୁସରଣ ସ୍ଥିତି ବଦଳିଲା',
      action_login: 'ଲଗଇନ ହେଲେ',
      action_matrimony_profile_admin_created: 'ଆଡମିନଙ୍କ ଦ୍ୱାରା ବିବାହ ପ୍ରୋଫାଇଲ ତିଆରି ହେଲା',
      action_matrimony_profile_submitted: 'ବିବାହ ପ୍ରୋଫାଇଲ ଦାଖଲ ହେଲା',
      action_matrimony_swipe: 'ବିବାହ ସ୍ୱାଇପ୍ ରେକର୍ଡ ହେଲା',
      action_member_banned: 'ସଦସ୍ୟ ପ୍ରତିବନ୍ଧିତ ହେଲେ',
      action_member_unbanned: 'ସଦସ୍ୟଙ୍କ ପ୍ରତିବନ୍ଧ ହଟାଗଲା',
      action_post_created: 'ପୋଷ୍ଟ ତିଆରି ହେଲା',
      action_post_liked: 'ପୋଷ୍ଟ ଲାଇକ୍ ହେଲା',
      action_profile_photo_updated: 'ପ୍ରୋଫାଇଲ ଫଟୋ ଅପଡେଟ୍ ହେଲା',
      action_report_approved: 'ରିପୋର୍ଟ ଅନୁମୋଦିତ ହେଲା',
      action_report_rejected: 'ରିପୋର୍ଟ ପ୍ରତ୍ୟାଖ୍ୟାନ ହେଲା',

      matrimonyTitle: 'ବିବାହ ପ୍ରାର୍ଥୀ',
      matrimonyAgeSuffix: 'ବର୍ଷ',
      matrimonyApprovedBadge: 'ଅନୁମୋଦିତ',
      matrimonySearchPlaceholder: 'ନାମ, ଗୋତ୍ର, ବୃତ୍ତି ଦ୍ୱାରା ଖୋଜନ୍ତୁ…',
      matrimonyEmptyTitle: 'କୌଣସି ପ୍ରାର୍ଥୀ ମିଳିଲେ ନାହିଁ',
      matrimonyEmptySubtitle: 'ଅନ୍ୟ ଏକ ସନ୍ଧାନ ଶବ୍ଦ ଚେଷ୍ଟା କରନ୍ତୁ',
      matrimonyLoadError: 'ପ୍ରାର୍ଥୀ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      matrimonyNameRequiredError: 'ଦୟାକରି ଏକ ନାମ ପ୍ରବେଶ କରନ୍ତୁ',
      matrimonySaveError: 'ପ୍ରାର୍ଥୀ ପ୍ରୋଫାଇଲ ସେଭ୍ କରିବାରେ ବିଫଳ',
      matrimonyDeleteError: 'ପ୍ରାର୍ଥୀ ପ୍ରୋଫାଇଲ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ',
      confirmDeleteCandidateTitle: 'ପ୍ରାର୍ଥୀ ଡିଲିଟ୍ କରନ୍ତୁ',
      confirmDeleteCandidateMessage: 'ଏହା ଏହି ପ୍ରାର୍ଥୀ ପ୍ରୋଫାଇଲକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିବ। ଏହା ପୂର୍ବାବସ୍ଥାକୁ ଫେରାଇ ହେବ ନାହିଁ। ଜାରି ରଖିବେ କି?',
      matrimonyBanError: 'ପ୍ରାର୍ଥୀ ସ୍ଥିତି ଅପଡେଟ୍ କରିବାରେ ବିଫଳ',
      confirmBanCandidateTitle: 'ପ୍ରାର୍ଥୀଙ୍କୁ ପ୍ରତିବନ୍ଧ କରନ୍ତୁ',
      confirmBanCandidateMessage: 'ଏହି ପ୍ରାର୍ଥୀ ପ୍ରୋଫାଇଲ ବିବାହ ବିଭାଗରୁ ଲୁଚିତ ରହିବ। ଜାରି ରଖିବେ କି?',
      confirmUnbanCandidateTitle: 'ପ୍ରାର୍ଥୀଙ୍କ ପ୍ରତିବନ୍ଧ ହଟାନ୍ତୁ',
      confirmUnbanCandidateMessage: 'ଏହି ପ୍ରାର୍ଥୀ ପ୍ରୋଫାଇଲକୁ ବିବାହ ବିଭାଗରେ ପୁନଃସ୍ଥାପନ କରିବେ କି?',
      matrimonyEditTitle: 'ପ୍ରାର୍ଥୀ ସମ୍ପାଦନ କରନ୍ତୁ',
      matrimonyCreateTitle: 'ନୂଆ ପ୍ରାର୍ଥୀ',
      matrimonyNameLabel: 'ନାମ',
      matrimonyGenderLabel: 'ଲିଙ୍ଗ',
      matrimonyGenderMale: 'ପୁରୁଷ',
      matrimonyGenderFemale: 'ମହିଳା',
      matrimonyDobLabel: 'ଜନ୍ମ ତାରିଖ',
      matrimonyAgeLabel: 'ବୟସ',
      matrimonyHeightLabel: 'ଉଚ୍ଚତା',
      matrimonyBloodGroupLabel: 'ରକ୍ତ ଗୋଷ୍ଠୀ',
      matrimonyGotraLabel: 'ଗୋତ୍ର',
      matrimonyBanshaLabel: 'ବଂଶ',
      matrimonyEducationLabel: 'ଶିକ୍ଷା',
      matrimonyTechnicalEducationLabel: 'ଟେକ୍ନିକାଲ ଶିକ୍ଷା',
      matrimonyProfessionalEducationLabel: 'ବୃତ୍ତିଗତ ଶିକ୍ଷା',
      matrimonyOccupationLabel: 'ବୃତ୍ତି',
      matrimonyFatherLabel: 'ପିତାଙ୍କ ନାମ',
      matrimonyMotherLabel: 'ମାତାଙ୍କ ନାମ',
      matrimonyAddressLabel: 'ଠିକଣା',
      matrimonyPhoneLabel: 'ଫୋନ୍',
      matrimonyEmailLabel: 'ଇମେଲ',

      postsTitle: 'ଫିଡ୍ ପୋଷ୍ଟ',
      postsSearchPlaceholder: 'ଲେଖକ କିମ୍ବା ବିଷୟବସ୍ତୁ ଦ୍ୱାରା ଖୋଜନ୍ତୁ…',
      postsLoadError: 'ପୋଷ୍ଟ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      postsEmptyTitle: 'କୌଣସି ପୋଷ୍ଟ ମିଳିଲା ନାହିଁ',
      postsEmptySubtitle: 'ଅନ୍ୟ ଏକ ସନ୍ଧାନ ଶବ୍ଦ ଚେଷ୍ଟା କରନ୍ତୁ',
      postActionError: 'ପୋଷ୍ଟ ଦୃଶ୍ୟମାନତା ଅପଡେଟ୍ କରିବାରେ ବିଫଳ',
      postDeleteError: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ',
      confirmDeletePostTitle: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ',
      confirmDeletePostMessage: 'ଏହା ପୋଷ୍ଟକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିବ। ଏହା ପୂର୍ବାବସ୍ଥାକୁ ଫେରାଇ ହେବ ନାହିଁ। ଜାରି ରଖିବେ କି?',
      postHiddenBadge: 'ଲୁଚିତ',
      postVisibleBadge: 'ଦୃଶ୍ୟମାନ',
      hideButton: 'ଲୁଚାନ୍ତୁ',
      unhideButton: 'ଦୃଶ୍ୟମାନ କରନ୍ତୁ',

      announcementsTitle: 'ଘୋଷଣା',
      announcementsLoadError: 'ଘୋଷଣା ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      announcementsEmptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଘୋଷଣା ନାହିଁ',
      announcementsEmptySubtitle: 'ଆପଣଙ୍କର ପ୍ରଥମ ଘୋଷଣା ତିଆରି କରିବାକୁ + ଦବାନ୍ତୁ',
      galleryPermissionDenied: 'ମିଡିଆ ବାଛିବାକୁ ଗ୍ୟାଲେରୀ ଅନୁମତି ଆବଶ୍ୟକ',
      announcementTitleRequiredError: 'ଦୟାକରି ଏକ ଶୀର୍ଷକ ପ୍ରବେଶ କରନ୍ତୁ',
      announcementSaveError: 'ଘୋଷଣା ସେଭ୍ କରିବାରେ ବିଫଳ',
      announcementDeleteError: 'ଘୋଷଣା ଡିଲିଟ୍ କରିବାରେ ବିଫଳ',
      confirmDeleteAnnouncementTitle: 'ଘୋଷଣା ଡିଲିଟ୍ କରନ୍ତୁ',
      confirmDeleteAnnouncementMessage: 'ଏହା ଏହି ଘୋଷଣାକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିବ। ଜାରି ରଖିବେ କି?',
      editButton: 'ସମ୍ପାଦନ',
      editAnnouncementTitle: 'ଘୋଷଣା ସମ୍ପାଦନ କରନ୍ତୁ',
      newAnnouncementTitle: 'ନୂଆ ଘୋଷଣା',
      announcementTitleLabel: 'ଶୀର୍ଷକ',
      announcementTitlePlaceholder: 'ଘୋଷଣା ଶୀର୍ଷକ',
      announcementContentLabel: 'ବିଷୟବସ୍ତୁ',
      announcementContentPlaceholder: 'ଘୋଷଣା ବିବରଣୀ ଲେଖନ୍ତୁ…',
      addImageLabel: 'ଛବି ଯୋଡ଼ନ୍ତୁ',
      replaceImageLabel: 'ଛବି ବଦଳାନ୍ତୁ',
      imageSelectedLabel: 'ଛବି ମନୋନୀତ ହେଲା',
      addVideoLabel: 'ଭିଡିଓ ଯୋଡ଼ନ୍ତୁ',
      replaceVideoLabel: 'ଭିଡିଓ ବଦଳାନ୍ତୁ',
      videoSelectedLabel: 'ଭିଡିଓ ମନୋନୀତ ହେଲା',

      expensesTitle: 'ସାମୁଦାୟିକ ଖର୍ଚ୍ଚ',
      expensesLoadError: 'ଖର୍ଚ୍ଚ ପ୍ରବିଷ୍ଟି ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      expensesEmptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପ୍ରବିଷ୍ଟି ନାହିଁ',
      expensesEmptySubtitle: 'ଏକ ଆୟ କିମ୍ବା ଖର୍ଚ୍ଚ ପ୍ରବିଷ୍ଟି ଯୋଡ଼ିବାକୁ + ଦବାନ୍ତୁ',
      expensesMigrationPendingTitle: 'ଖର୍ଚ୍ଚ ଟ୍ରାକିଂ ଏପର୍ଯ୍ୟନ୍ତ ସକ୍ରିୟ ହୋଇନାହିଁ',
      expensesMigrationPendingSubtitle: 'ଏକ ବକେୟା ଅପଡେଟ୍ ପ୍ରୟୋଗ ହେଲାପରେ ଏହି ବିଶେଷତା ଉପଲବ୍ଧ ହେବ',
      expenseFilterAll: 'ସମସ୍ତ',
      expenseFilterIncome: 'ଆୟ',
      expenseFilterExpense: 'ଖର୍ଚ୍ଚ',
      summaryIncomeLabel: 'ଆୟ',
      summaryExpenseLabel: 'ଖର୍ଚ୍ଚ',
      summaryBalanceLabel: 'ବାକି ପାଣ୍ଠି',
      expenseTitleRequiredError: 'ଦୟାକରି ଏକ ଶୀର୍ଷକ ପ୍ରବେଶ କରନ୍ତୁ',
      expenseAmountRequiredError: 'ଦୟାକରି ଏକ ବୈଧ ପରିମାଣ ପ୍ରବେଶ କରନ୍ତୁ',
      expenseSaveError: 'ପ୍ରବିଷ୍ଟି ସେଭ୍ କରିବାରେ ବିଫଳ',
      expenseDeleteError: 'ପ୍ରବିଷ୍ଟି ଡିଲିଟ୍ କରିବାରେ ବିଫଳ',
      confirmDeleteExpenseTitle: 'ପ୍ରବିଷ୍ଟି ଡିଲିଟ୍ କରନ୍ତୁ',
      confirmDeleteExpenseMessage: 'ଏହା ଏହି ଲେଜର୍ ପ୍ରବିଷ୍ଟିକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିବ। ଜାରି ରଖିବେ କି?',
      editExpenseTitle: 'ପ୍ରବିଷ୍ଟି ସମ୍ପାଦନ କରନ୍ତୁ',
      newExpenseTitle: 'ନୂଆ ପ୍ରବିଷ୍ଟି',
      expenseTitleLabel: 'ଶୀର୍ଷକ',
      expenseTitlePlaceholder: 'ଯଥା ବାର୍ଷିକ ସଦସ୍ୟତା ଶୁଳ୍କ',
      expenseAmountLabel: 'ପରିମାଣ (₹)',
      expenseAmountPlaceholder: 'ପରିମାଣ ପ୍ରବେଶ କରନ୍ତୁ',
      expenseCategoryLabel: 'ବର୍ଗ (ବୈକଳ୍ପିକ)',
      expenseCategoryPlaceholder: 'ଯଥା ଅନୁଷ୍ଠାନ, ଦାନ',
      expenseDateLabel: 'ତାରିଖ (ବୈକଳ୍ପିକ, YYYY-MM-DD)',
      expenseDatePlaceholder: 'ଯଥା 2026-07-26',
      expenseNoteLabel: 'ଟିପ୍ପଣୀ (ବୈକଳ୍ପିକ)',
      expenseNotePlaceholder: 'ଅତିରିକ୍ତ ବିବରଣୀ…',

      settingsTitle: 'ଆଡମିନ ସେଟିଂ',
      accountInfoHeader: 'ଖାତା ସୂଚନା',
      changePasswordHeader: 'ପାସୱାର୍ଡ ବଦଳାନ୍ତୁ',
      currentPasswordLabel: 'ବର୍ତ୍ତମାନ ପାସୱାର୍ଡ',
      currentPasswordPlaceholder: 'ବର୍ତ୍ତମାନ ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ',
      newPasswordLabel: 'ନୂଆ ପାସୱାର୍ଡ',
      newPasswordPlaceholder: 'ନୂଆ ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ',
      confirmPasswordLabel: 'ନୂଆ ପାସୱାର୍ଡ ନିଶ୍ଚିତ କରନ୍ତୁ',
      confirmPasswordPlaceholder: 'ନୂଆ ପାସୱାର୍ଡ ପୁନର୍ବାର ପ୍ରବେଶ କରନ୍ତୁ',
      currentPasswordRequiredError: 'ଦୟାକରି ଆପଣଙ୍କର ବର୍ତ୍ତମାନ ପାସୱାର୍ଡ ପ୍ରବେଶ କରନ୍ତୁ',
      newPasswordTooShortError: 'ନୂଆ ପାସୱାର୍ଡ ଅତି କମରେ ୬ ଅକ୍ଷରର ହେବା ଆବଶ୍ୟକ',
      passwordsDontMatchError: 'ନୂଆ ପାସୱାର୍ଡ ଏବଂ ନିଶ୍ଚିତକରଣ ମେଳ ଖାଉ ନାହିଁ',
      passwordChangedSuccess: 'ପାସୱାର୍ଡ ସଫଳତାର ସହ ଅପଡେଟ୍ ହେଲା',
      passwordChangeError: 'ପାସୱାର୍ଡ ବଦଳାଇବାରେ ବିଫଳ',
    },
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (section: string, key: string) => string;
}

const LanguageContext = createContext<LangContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>('en');

  useEffect(() => {
    storage.getItem(STORAGE_KEYS.LANGUAGE).then((saved) => {
      if (saved === 'en' || saved === 'od') setLangState(saved);
    });
  }, []);

  const setLang = async (l: Lang) => {
    setLangState(l);
    await storage.setItem(STORAGE_KEYS.LANGUAGE, l);
  };

  const t = (section: string, key: string): string => {
    return (translations[lang] as any)?.[section]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
