// src/context/LanguageContext.tsx
import React, { createContext, useContext, useState, useEffect } from 'react';
import { storage } from '../utils/secureStorage';
import { STORAGE_KEYS } from '../config/constants';

type Lang = 'en' | 'od';

// Port all translations from web LanguageContext exactly
const translations = {
  en: {
    nav: {
      home: 'Home', explore: 'Explore', groups: 'Groups',
      events: 'Events', messages: 'Messages', notifications: 'Notifications',
      members: 'Members', gallery: 'Gallery', profile: 'Profile', settings: 'Settings',
    },
    common: {
      appName: 'Pandara Samaja', appTagline: 'COMMUNITY PORTAL',
      logout: 'Logout', collapse: 'Collapse', expand: 'Expand',
      loading: 'Loading...', error: 'Something went wrong',
      cancel: 'Cancel', save: 'Save', reset: 'Reset', delete: 'Delete',
      retry: 'Retry', ok: 'OK', back: '← Back',
      errorTitle: 'Error', successTitle: 'Success',
      comingSoon: 'Coming in Phase 2',
      loadErrorMessage: 'Could not load content. Check your connection and try again.',
      globalSearchPlaceholder: 'Search members, posts, tags…',
      searching: 'Searching…',
      topResults: 'Top Results',
      securityCheckTitle: 'Security Check in Progress',
      securityCheckMessage: 'Please wait a moment while we establish a secure connection.',
    },
    feed: {
      noPostsTitle: 'No posts yet', noPostsSubtitle: 'Be the first to share something',
      loadError: 'Failed to load community feed.',
      commentError: 'Failed to submit comment.', replyError: 'Failed to submit reply.',
      postError: 'Failed to submit post.', deleteError: 'Failed to delete post.',
      editError: 'Failed to update post.', reportError: 'Failed to submit report.',
      reportSuccessTitle: 'Report Submitted',
      reportSuccessMessage: 'Thank you for keeping our community safe. We will review this post.',
      storySuccessMessage: 'Story uploaded successfully!', storyError: 'Failed to upload story.',
    },
    notifications: {
      title: 'Notifications',
      markAllRead: 'Mark all read',
      allCaughtUpTitle: 'All caught up', allCaughtUpSubtitle: 'No new notifications',
      loadError: 'Failed to load notifications',
    },
    chat: {
      title: 'Direct Messages',
      searchPlaceholder: 'Search conversations...',
      noConversationsTitle: 'No Conversations',
      noConversationsSubtitle: 'Start a chat from the member directory to connect.',
      online: 'Online', offline: 'Offline',
      messagePlaceholder: 'Type a message...',
      loadError: 'Failed to load conversations.', sendError: 'Failed to send message.',
    },
    settings: {
      title: 'Settings',
      preferencesHeader: 'Preferences',
      pushNotifTitle: 'Push Notifications', pushNotifDesc: 'Alerts for posts, likes & replies',
      eventRemindersTitle: 'Event Reminders', eventRemindersDesc: 'Notifications for upcoming events',
      emailUpdatesTitle: 'Email Updates', emailUpdatesDesc: 'Monthly newsletters & summaries',
      appearanceHeader: 'Appearance',
      themeLight: 'Light', themeDark: 'Dark', themeSystem: 'System',
      languageHeader: 'Language', activeLanguage: 'Active language',
      helpSupportHeader: 'Help & Support',
      whatsappSupport: 'WhatsApp Support',
      privacyPolicy: 'Privacy Policy', termsOfService: 'Terms of Service',
      accountHeader: 'Account', logoutButton: 'Logout',
      confirmLogoutTitle: 'Confirm Logout',
      confirmLogoutMessage: 'Are you sure you want to log out of your account?',
      supportAlertMessage: 'Connecting to WhatsApp Support... (+91 99999 99999)',
      footerName: 'Nikhila Odisha Pandara Samaja',
    },
    auth: {
      memberLoginTitle: 'Member Login',
      membershipNumberLabel: 'Membership Number', membershipPlaceholder: 'e.g. MEM1234567',
      mobileNumberLabel: 'Mobile Number', mobilePlaceholder: '10-digit mobile number',
      sendOtpButton: 'Send OTP',
      membershipRequiredError: 'Please enter your Membership Number',
      mobileRequiredError: 'Please enter a valid 10-digit mobile number',
      sendOtpError: 'Failed to send OTP. Please try again.',
      whatsappNotInstalled: 'WhatsApp is not installed on your device',
      helpSupportTitle: 'Help & Support',
      noMembershipNo: "Don't have a Membership No.?", getOnWhatsapp: 'Get it on WhatsApp →',
      updateMobileNo: 'Need to register/update Mobile No.?', updateOnWhatsapp: 'Update on WhatsApp →',
      notAMemberYet: 'New here? Not a member yet?', contactToRegister: 'Contact us on WhatsApp to register →',
      termsFooter: 'By logging in, you agree to our Terms & Privacy Policy',
      enterOtpTitle: 'Enter OTP', otpSentTo: 'OTP sent to',
      verifyButton: 'Verify & Login',
      invalidOtpError: 'Invalid OTP. Please try again.',
      resendOtpIn: 'Resend OTP in', resendOtp: 'Resend OTP',
    },
    onboarding: {
      slide1Title: 'Welcome to Pandara Samaja',
      slide1Body: 'Connect with 10,000+ members of the Nikhila Odisha Pandara Samaja community across Odisha.',
      slide2Title: 'Your Family, Connected',
      slide2Body: 'Explore the community member directory. Follow, message, and stay connected with your people.',
      slide3Title: 'Stay Informed',
      slide3Body: 'Get community announcements, event updates, leader news, and matrimony listings — all in one place.',
      slide4Title: 'Members Only',
      slide4Body: 'Login with your registered mobile number. Your data is secure and only visible to community members.',
      skip: 'Skip', next: 'Next →', getStarted: 'Get Started',
    },
    announcements: {
      title: 'Announcements',
      officialUpdate: 'Official Update',
      defaultTitle: 'Official Announcement',
      loadError: 'Failed to load official announcements.',
      emptyTitle: 'No Announcements Yet',
      emptySubtitle: 'Check back later for official updates from the admins.',
    },
    events: {
      title: 'Events',
      communityEvents: 'Community Events',
      calendarSubtitle: 'ସମାଜ କାର୍ଯ୍ୟକ୍ରମ — Events Calendar',
      loadError: 'Failed to load community events.',
      rsvpSuccessTitle: 'RSVP Registered',
      rsvpSuccessMessage: 'Successfully registered for this event!',
      rsvpError: 'Failed to submit RSVP registration.',
      tabUpcoming: 'Upcoming', tabPast: 'Past Events', tabRsvped: 'My RSVPs',
      locationTBA: 'TBA',
      attending: 'attending',
      registered: '✓ Registered',
      rsvpNow: 'RSVP Now',
      noRsvpsTitle: 'No RSVPs', noRsvpsSubtitle: "You haven't RSVPed to any events yet.",
      noUpcomingTitle: 'No upcoming events', noUpcomingSubtitle: 'Check back later',
    },
    groups: {
      title: 'Community Groups',
      loadError: 'Failed to fetch groups',
      joinedTitle: 'Joined Group!', leftTitle: 'Left Group!',
      joinedMessagePrefix: 'You are now a member of', joinedMessageSuffix: '',
      leftMessagePrefix: 'You left', leftMessageSuffix: '',
      searchPlaceholder: 'Search groups...',
      verifiedGroup: 'Verified Group',
      joined: 'Joined ✓', joinGroup: 'Join Group',
      emptyTitle: 'No Groups Found', emptySubtitle: 'Try adjusting your search query or categories.',
      showAllGroups: 'Show All Groups',
      categoryAll: 'All Groups', categoryRegional: 'Regional', categoryMatrimony: 'Matrimony',
      categoryYouth: 'Youth', categorySocial: 'Social', categoryProfessional: 'Professional',
    },
    leaders: {
      title: 'Leaders',
      communityLeaders: 'Community Leaders',
      leadershipSubtitle: 'ସମାଜ ନେତୃତ୍ୱ — Leadership Tiers',
      levelState: 'State', levelStateOr: 'ରାଜ୍ୟ',
      levelDistrict: 'District', levelDistrictOr: 'ଜିଲ୍ଲା',
      levelTaluka: 'Taluka', levelTalukaOr: 'ତାଲୁକ',
      levelPanchayat: 'Panchayat', levelPanchayatOr: 'ପଞ୍ଚାୟତ',
      locationPrefix: 'Location:', selectPrefix: 'Select', choose: 'Choose ▾',
      loadingLeaders: 'Loading leaders…',
      emptyTitle: 'No leaders found', emptySubtitle: 'No leader cards have been registered under this tier.',
      selectLocationTitle: 'Select Location', allPrefix: 'All',
      searchPlaceholder: 'Search by name, role, or location…',
      noSearchResultsTitle: 'No matching leaders', noSearchResultsSubtitle: 'Try a different name, role, or location.',
    },
    matrimony: {
      title: 'Matrimony Services',
      verifiedBanner: 'All matrimony profiles are 100% verified by Samaja.',
      filterAll: 'All Candidates', filterBrides: 'Brides ♀', filterGrooms: 'Grooms ♂',
      groomTag: 'Groom ♂', brideTag: 'Bride ♀',
      gotraLabel: 'Gotra:',
      interestExpressedCard: 'Interest Expressed', interestExpressedModal: 'Interest Expressed ✓',
      emptyTitle: 'No Profiles Found', emptySubtitle: 'No profiles match your current selection filter.',
      resetFilter: 'Reset Filter',
      profileDetailsHeader: 'Profile Details',
      heightLabel: 'Height', educationLabel: 'Education', occupationLabel: 'Occupation',
      parentsLabel: 'Parents / Guardians', locationLabel: 'Location',
      yearsAbbrev: 'yrs',
      sendInterest: 'Send Interest',
      shortlistAddedTitle: 'Added to Shortlist', shortlistRemovedTitle: 'Removed from Shortlist',
      shortlistAddedMessagePrefix: 'You have shortlisted', shortlistAddedMessageSuffix: '',
      shortlistRemovedMessagePrefix: 'You removed', shortlistRemovedMessageSuffix: 'from shortlist',
      interestExpressedToastTitle: 'Interest Expressed!', interestRetractedToastTitle: 'Interest Retracted',
      interestExpressedMessagePrefix: 'A request has been sent to', interestExpressedMessageSuffix: "'s family.",
      interestCanceledMessagePrefix: 'You canceled interest in', interestCanceledMessageSuffix: '',
    },
    members: {
      title: 'Members',
      loadError: 'Failed to load members',
      searchPlaceholder: 'Name · #no · village · mobile…',
      matchingPrefix: 'matching',
      countSuffix: 'members',
      noMembersTitle: 'No members found',
      noMembersSubtitle: 'Try adjusting your search or filters',
      allLoadedPrefix: 'All', allLoadedSuffix: 'members loaded',
      maleHof: '♂ Male HoF', femaleHof: '♀ Female HoF',
      // Filter modal
      filterModalTitle: 'Filter Members',
      districtSectionTitle: 'District', talukaSectionTitle: 'Taluka',
      panchayatSectionTitle: 'Panchayat', villageSectionTitle: 'Village',
      genderSectionTitle: 'Head of Family Gender',
      allDistricts: 'All Districts',
      allTalukasInPrefix: 'All Talukas in', allPanchayatsInPrefix: 'All Panchayats in', allVillagesInPrefix: 'All Villages in',
      allGenders: 'All Genders', maleHead: '♂ Male Head', femaleHead: '♀ Female Head',
      resetButton: 'Reset',
      showResultsPrefix: 'Show', showResultsSuffix: 'Results',
      // Member card
      activeBadge: 'ACTIVE',
      headGenderTitle: 'Head Gender',
      genderFemaleTag: '♀ Female', genderMaleTag: '♂ Male',
      maleWord: 'Male', femaleWord: 'Female',
      familyMembersListLabel: 'Family Members List',
    },
    memberProfile: {
      notFoundText: 'Profile not found or restricted.',
      returnToMembers: '← Return to Members',
      backLabel: '← Back',
      followingLabel: 'Following', followLabel: 'Follow', messageLabel: 'Message',
      headOfFamily: 'Head of Family',
      joinedPrefix: 'Joined',
      postsTabLabel: 'Posts', familyTabLabel: 'Family', galleryTabLabel: 'Gallery',
      statsFollowersLabel: 'Followers',
      familyMembersHeader: 'Family Members',
      noPostsTitle: 'No posts yet', noPostsSubtitle: "This member hasn't posted yet",
      noPhotosTitle: 'No photos', noPhotosSubtitle: 'No photos shared yet',
    },
    profile: {
      title: 'My Profile',
      settingsButton: 'Settings',
      memberBadge: 'Pandara Member',
      headOfFamily: 'Head of Family',
      mobilePrefix: 'Mobile:',
      familyHubHeader: 'Family Hub',
      familyTreeLabel: 'Family Tree', familyTreeDesc: 'Genealogy tree',
      matrimonyLabel: 'Matrimony', matrimonyDesc: 'Find matches',
      familyAlbumsLabel: 'Family Albums', familyAlbumsDesc: 'Shared gallery',
      familyEventsLabel: 'Family Events', familyEventsDesc: 'Rsvped events',
      addressInfoHeader: 'Address Information',
      villageLabel: 'Village', panchayatLabel: 'Panchayat', fullAddressLabel: 'Full Address',
      notSpecified: 'Not specified',
      villagePlaceholder: 'Village name', panchayatPlaceholder: 'Panchayat name', addressPlaceholder: 'Full address details',
      familyMembersHeader: 'Family Members',
      noFamilyMembers: 'No family members registered.',
      yrsAbbrev: 'yrs',
      profilePhotoTitle: 'Profile Photo', profilePhotoMessage: 'Change or remove your profile picture.',
      removePhoto: 'Remove Photo', removedTitle: 'Removed', removedMessage: 'Profile photo removed.',
      uploadNewPhoto: 'Upload New Photo', uploadTitle: 'Upload', uploadMessage: 'Photo upload simulated.',
      profileSavedTitle: 'Profile Saved', profileSavedMessage: 'Your address details have been updated.',
    },
    familyTree: {
      title: 'Family Tree',
      subtitle: 'Your family, visualized',
      headOfFamily: 'Head of Family',
      membershipPrefix: 'Membership #',
      groupSpouse: 'Spouse',
      groupParents: 'Parents',
      groupChildren: 'Children',
      groupOthers: 'Other Family Members',
      ageSuffix: 'yrs',
      emptyTitle: 'No Family Data',
      emptySubtitle: 'Your family details have not been added to your profile yet.',
    },
    familyAlbums: {
      title: 'Family Albums',
      subtitle: 'Photos shared within your family',
      loadError: 'Failed to load family albums.',
      createAlbum: 'Create Album',
      newAlbumTitle: 'New Album',
      albumTitleLabel: 'Title',
      albumTitlePlaceholder: 'e.g. Diwali 2025',
      albumDescriptionLabel: 'Description',
      albumDescriptionPlaceholder: 'Add a short description (optional)',
      coverPhotoLabel: 'Cover Photo (optional)',
      chooseCoverPhoto: 'Choose Cover Photo',
      changeCoverPhoto: 'Change Cover Photo',
      createButton: 'Create Album',
      creatingButton: 'Creating…',
      titleRequiredError: 'Please enter an album title.',
      createError: 'Failed to create album.',
      createSuccessTitle: 'Album Created',
      createSuccessMessage: 'Your new family album is ready.',
      photosCountSuffix: 'photos',
      photoCountSingular: 'photo',
      emptyTitle: 'No Albums Yet',
      emptySubtitle: 'Create your first family album to start sharing photos.',
      deleteAlbumConfirmTitle: 'Delete Album',
      deleteAlbumConfirmMessage: 'This will permanently delete this album and all its photos. Continue?',
      deleteError: 'Failed to delete album.',
      deleteSuccessMessage: 'Album deleted.',
      addPhotos: 'Add Photos',
      addingPhotos: 'Uploading…',
      addPhotosError: 'Failed to add photos.',
      addPhotosSuccessMessage: 'Photos added to album.',
      noPhotosInAlbum: 'No photos in this album yet.',
      cancelButton: 'Cancel',
      closeButton: 'Close',
    },
    familyEvents: {
      title: 'Family Events',
      subtitle: 'Events for your own family',
      loadError: 'Failed to load family events.',
      createEvent: 'Create Event',
      newEventTitle: 'New Family Event',
      eventTitleLabel: 'Title',
      eventTitlePlaceholder: "e.g. Grandma's Birthday",
      descriptionLabel: 'Description',
      descriptionPlaceholder: 'Add details (optional)',
      dateLabel: 'Date',
      datePlaceholder: 'YYYY-MM-DD',
      locationLabel: 'Location',
      locationPlaceholder: 'Where is it happening?',
      typeLabel: 'Type',
      typePlaceholder: 'e.g. Birthday, Anniversary, Gathering',
      createButton: 'Create Event',
      creatingButton: 'Creating…',
      titleRequiredError: 'Please enter an event title.',
      dateRequiredError: 'Please enter a valid date (YYYY-MM-DD).',
      createError: 'Failed to create event.',
      createSuccessTitle: 'Event Created',
      createSuccessMessage: 'Your family event has been added.',
      emptyTitle: 'No Family Events',
      emptySubtitle: 'Create an event to start planning with your family.',
      deleteEventConfirmTitle: 'Delete Event',
      deleteEventConfirmMessage: 'Are you sure you want to delete this event?',
      deleteError: 'Failed to delete event.',
      deleteSuccessMessage: 'Event deleted.',
      tabUpcoming: 'Upcoming',
      tabPast: 'Past',
      rsvpGoing: 'Going',
      rsvpMaybe: 'Maybe',
      rsvpNotGoing: 'Not Going',
      rsvpError: 'Failed to submit RSVP.',
      locationTBA: 'TBA',
      cancelButton: 'Cancel',
    },
    explore: {
      title: 'Explore',
      tabTrending: 'Trending', tabMembers: 'Members', tabHashtags: 'Hashtags',
      trendingPostsTitle: 'Trending Posts',
      trendingPostsSubtitle: 'Posts with the most engagement across the community. (Coming Soon)',
      activeMembersLabel: 'Total Members Active Today',
      noPopularMembers: 'No popular members data available.',
      noTags: 'No tags available at the moment.',
    },
    feedComponents: {
      warningTitle: 'Warning',
      inappropriateCommentMessage: 'Your comment contains inappropriate content.',
      cancelButtonLabel: 'Cancel',
      saveButtonLabel: 'Save',
      deleteButtonLabel: 'Delete',
      commentWord: 'comment',
      commentsWordPlural: 'comments',
      likeLabel: 'Like',
      likedLabel: 'Liked',
      replyLabel: 'Reply',
      writeReplyPlaceholder: 'Write a reply...',
      noCommentsYetText: 'No comments yet',
      loadMoreCommentsLabel: 'Load more comments',
      writeCommentPlaceholder: 'Write a comment...',
      editPostLabel: 'Edit Post',
      deletePostLabel: 'Delete Post',
      savePostLabel: 'Save Post',
      unsavePostLabel: 'Unsave Post',
      reportPostLabel: 'Report Post',
      deletePostConfirmTitle: 'Delete Post',
      deletePostConfirmMessage: 'Are you sure you want to delete this post?',
      reportPostModalTitle: 'Report Post',
      reportPostPrompt: 'Why are you reporting this post?',
      submitReportLabel: 'Submit Report',
      reportReasonAdult: 'Adult / Sexual content',
      reportReasonHarassment: 'Harassment or bullying',
      reportReasonHateSpeech: 'Hate speech',
      reportReasonSpam: 'Spam or misleading',
      reportReasonViolence: 'Violence or dangerous content',
      reportReasonFalseInfo: 'False information',
      reportReasonOther: 'Other',
      sharePostTitlePrefix: 'Post by',
      genericErrorTitle: 'Error',
      postValidationErrorMessage: 'Please enter some text or add media/poll.',
      inappropriateContentTitle: 'Inappropriate Content',
      inappropriateContentMessage: 'Your post contains banned words.',
      shareSomethingPlaceholder: 'Share something with the community...',
      createPostTitle: 'Create Post',
      postButtonLabel: 'Post',
      postingToMemberPortal: 'Posting to Member Portal',
      whatsOnYourMindPlaceholder: "What's on your mind? (Use #tags or @mentions)",
      enterLocationPlaceholder: 'Enter location tag...',
      createPollTitle: 'Create Poll',
      pollLimitReachedTitle: 'Limit Reached',
      pollLimitReachedMessage: 'You can add up to 5 options.',
      pollMinOptionsTitle: 'Required',
      pollMinOptionsMessage: 'A poll requires at least 2 options.',
      pollQuestionRequiredMessage: 'Please enter a poll question.',
      pollOptionsRequiredMessage: 'Please enter at least 2 valid options.',
      pollQuestionLabel: 'Question',
      pollQuestionPlaceholder: 'What would you like to ask?',
      pollOptionsLabel: 'Options',
      pollOptionPlaceholderPrefix: 'Option',
      addOptionLabel: 'Add Option',
      createButtonLabel: 'Create',
      voteWord: 'vote',
      votesWordPlural: 'votes',
      pollEndsPrefix: 'Ends',
      addStoryLabel: 'Add Story',
    },
  },
  od: {
    nav: {
      home: 'ଘର', explore: 'ଅନ୍ୱେଷଣ', groups: 'ଦଳ',
      events: 'ଅନୁଷ୍ଠାନ', messages: 'ବାର୍ତ୍ତା', notifications: 'ବିଜ୍ଞପ୍ତି',
      members: 'ସଦସ୍ୟ', gallery: 'ଗ୍ୟାଲେରୀ', profile: 'ପ୍ରୋଫାଇଲ', settings: 'ସେଟିଂ',
    },
    common: {
      appName: 'ପଣ୍ଡାର ସମାଜ', appTagline: 'ସାମୁଦାୟିକ ପୋର୍ଟାଲ',
      logout: 'ଲଗ୍ ଆଉଟ', collapse: 'ସଂକୁଚିତ', expand: 'ବିସ୍ତାର',
      loading: 'ଲୋଡ ହେଉଛି...', error: 'କିଛି ଭୁଲ ହୋଇଗଲା',
      cancel: 'ବାତିଲ', save: 'ସେଭ୍', reset: 'ପୁନଃସେଟ୍', delete: 'ଡିଲିଟ୍',
      retry: 'ପୁନଃ ଚେଷ୍ଟା', ok: 'ଠିକ୍ ଅଛି', back: '← ପଛକୁ',
      errorTitle: 'ତ୍ରୁଟି', successTitle: 'ସଫଳ',
      comingSoon: 'ପର୍ଯ୍ୟାୟ ୨ ରେ ଆସୁଛି',
      loadErrorMessage: 'ବିଷୟବସ୍ତୁ ଲୋଡ୍ କରିପାରିଲା ନାହିଁ। ଆପଣଙ୍କ ସଂଯୋଗ ଯାଞ୍ଚ କରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      globalSearchPlaceholder: 'ସଦସ୍ୟ, ପୋଷ୍ଟ, ଟ୍ୟାଗ୍ ଖୋଜନ୍ତୁ…',
      searching: 'ଖୋଜୁଛି…',
      topResults: 'ଶୀର୍ଷ ଫଳାଫଳ',
      securityCheckTitle: 'ସୁରକ୍ଷା ଯାଞ୍ଚ ଚାଲୁଛି',
      securityCheckMessage: 'ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ, ଆମେ ଏକ ସୁରକ୍ଷିତ ସଂଯୋଗ ସ୍ଥାପନ କରୁଛୁ।',
    },
    feed: {
      noPostsTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପୋଷ୍ଟ ନାହିଁ', noPostsSubtitle: 'କିଛି ସେୟାର କରିବାରେ ପ୍ରଥମ ହୁଅନ୍ତୁ',
      loadError: 'ସାମୁଦାୟିକ ଫିଡ୍ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      commentError: 'ମନ୍ତବ୍ୟ ଦାଖଲ କରିବାରେ ବିଫଳ।', replyError: 'ଉତ୍ତର ଦାଖଲ କରିବାରେ ବିଫଳ।',
      postError: 'ପୋଷ୍ଟ ଦାଖଲ କରିବାରେ ବିଫଳ।', deleteError: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ।',
      editError: 'ପୋଷ୍ଟ ଅପଡେଟ୍ କରିବାରେ ବିଫଳ।', reportError: 'ରିପୋର୍ଟ ଦାଖଲ କରିବାରେ ବିଫଳ।',
      reportSuccessTitle: 'ରିପୋର୍ଟ ଦାଖଲ ହେଲା',
      reportSuccessMessage: 'ଆମ ସମାଜକୁ ସୁରକ୍ଷିତ ରଖିବାପାଇଁ ଧନ୍ୟବାଦ। ଆମେ ଏହି ପୋଷ୍ଟକୁ ସମୀକ୍ଷା କରିବୁ।',
      storySuccessMessage: 'ଷ୍ଟୋରୀ ସଫଳତାର ସହ ଅପଲୋଡ୍ ହେଲା!', storyError: 'ଷ୍ଟୋରୀ ଅପଲୋଡ୍ କରିବାରେ ବିଫଳ।',
    },
    notifications: {
      title: 'ବିଜ୍ଞପ୍ତି',
      markAllRead: 'ସବୁ ପଢ଼ାଯାଇଛି ବୋଲି ଚିହ୍ନଟ କରନ୍ତୁ',
      allCaughtUpTitle: 'ସବୁ ଦେଖାଗଲା', allCaughtUpSubtitle: 'କୌଣସି ନୂଆ ବିଜ୍ଞପ୍ତି ନାହିଁ',
      loadError: 'ବିଜ୍ଞପ୍ତି ଲୋଡ୍ କରିବାରେ ବିଫଳ',
    },
    chat: {
      title: 'ସନ୍ଦେଶ',
      searchPlaceholder: 'ସନ୍ଦେଶ ବା ସଦସ୍ୟ ଖୋଜନ୍ତୁ...',
      noConversationsTitle: 'କୌଣସି ଆଲାପ ମିଳିଲା ନାହିଁ',
      noConversationsSubtitle: 'ସଦସ୍ୟ ତାଲିକାରୁ ଯାଇ ଚାଟ୍ ଆରମ୍ଭ କରନ୍ତୁ',
      online: 'ଅନଲାଇନ', offline: 'ଅଫଲାଇନ',
      messagePlaceholder: 'ବାର୍ତ୍ତା ଲେଖନ୍ତୁ...',
      loadError: 'ଆଲାପ ଲୋଡ୍ କରିବାରେ ବିଫଳ।', sendError: 'ବାର୍ତ୍ତା ପଠାଇବାରେ ବିଫଳ।',
    },
    settings: {
      title: 'ସେଟିଂ',
      preferencesHeader: 'ପସନ୍ଦ',
      pushNotifTitle: 'ପୁସ୍ ବିଜ୍ଞପ୍ତି', pushNotifDesc: 'ନୂଆ ପୋଷ୍ଟ ଓ ବାର୍ତ୍ତା ପାଇଁ ବିଜ୍ଞପ୍ତି',
      eventRemindersTitle: 'ଅନୁଷ୍ଠାନ ମନେପକାନ୍ତୁ', eventRemindersDesc: 'ଆଗାମୀ ସଭା ଓ ସାମାଜିକ ଅନୁଷ୍ଠାନ',
      emailUpdatesTitle: 'ଇମେଲ ଅପଡେଟ', emailUpdatesDesc: 'ମାସିକ ସମାଚାର ପତ୍ରିକା',
      appearanceHeader: 'ରୂପ',
      themeLight: 'ଆଲୋକ', themeDark: 'ଅନ୍ଧାର', themeSystem: 'ସିଷ୍ଟମ',
      languageHeader: 'ଭାଷା', activeLanguage: 'ସକ୍ରିୟ ଭାଷା',
      helpSupportHeader: 'ସହାୟତା',
      whatsappSupport: 'ହ୍ଵାଟସ୍‌ଆପ୍ ସହାୟତା',
      privacyPolicy: 'ଗୋପନୀୟତା ନୀତି', termsOfService: 'ସେବା ସର୍ତ୍ତାବଳୀ',
      accountHeader: 'ଖାତା', logoutButton: 'ଲଗ୍ ଆଉଟ୍ କରନ୍ତୁ',
      confirmLogoutTitle: 'ଲଗ୍ ଆଉଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
      confirmLogoutMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଲଗ୍ ଆଉଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      supportAlertMessage: 'ସହାୟତା ସେବା ଶୀଘ୍ର ଉପଲବ୍ଧ ହେବ।',
      footerName: 'ନିଖିଳ ଓଡ଼ିଶା ପଣ୍ଡାର ସମାଜ',
    },
    auth: {
      memberLoginTitle: 'ସଦସ୍ୟ ଲଗଇନ',
      membershipNumberLabel: 'ସଦସ୍ୟତା ନମ୍ବର', membershipPlaceholder: 'ଯଥା MEM1234567',
      mobileNumberLabel: 'ମୋବାଇଲ ନମ୍ବର', mobilePlaceholder: '୧୦-ଅଙ୍କ ମୋବାଇଲ ନମ୍ବର',
      sendOtpButton: 'OTP ପଠାନ୍ତୁ',
      membershipRequiredError: 'ଦୟାକରି ଆପଣଙ୍କର ସଦସ୍ୟତା ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
      mobileRequiredError: 'ଦୟାକରି ଏକ ବୈଧ ୧୦-ଅଙ୍କ ମୋବାଇଲ ନମ୍ବର ପ୍ରବେଶ କରନ୍ତୁ',
      sendOtpError: 'OTP ପଠାଇବାରେ ବିଫଳ। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      whatsappNotInstalled: 'ଆପଣଙ୍କ ଡିଭାଇସରେ ହ୍ଵାଟସ୍‌ଆପ୍ ଇନଷ୍ଟଲ ହୋଇନାହିଁ',
      helpSupportTitle: 'ସହାୟତା',
      noMembershipNo: 'ସଦସ୍ୟତା ନମ୍ବର ନାହିଁ?', getOnWhatsapp: 'ହ୍ଵାଟସ୍‌ଆପ୍‌ରେ ପାଆନ୍ତୁ →',
      updateMobileNo: 'ମୋବାଇଲ ନମ୍ବର ପଞ୍ଜିକରଣ/ଅପଡେଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି?', updateOnWhatsapp: 'ହ୍ଵାଟସ୍‌ଆପ୍‌ରେ ଅପଡେଟ୍ କରନ୍ତୁ →',
      notAMemberYet: 'ନୂଆ ଆସିଛନ୍ତି? ଏପର୍ଯ୍ୟନ୍ତ ସଦସ୍ୟ ନୁହଁନ୍ତି?', contactToRegister: 'ପଞ୍ଜିକରଣ ପାଇଁ ହ୍ଵାଟସ୍‌ଆପ୍‌ରେ ଯୋଗାଯୋଗ କରନ୍ତୁ →',
      termsFooter: 'ଲଗଇନ କରି, ଆପଣ ଆମର ସର୍ତ୍ତାବଳୀ ଓ ଗୋପନୀୟତା ନୀତିରେ ସହମତ ହେଉଛନ୍ତି',
      enterOtpTitle: 'OTP ପ୍ରବେଶ କରନ୍ତୁ', otpSentTo: 'ଏଠାକୁ OTP ପଠାଗଲା',
      verifyButton: 'ଯାଞ୍ଚ କରନ୍ତୁ ଓ ଲଗଇନ କରନ୍ତୁ',
      invalidOtpError: 'ଅବୈଧ OTP। ଦୟାକରି ପୁନର୍ବାର ଚେଷ୍ଟା କରନ୍ତୁ।',
      resendOtpIn: 'ପୁନଃ OTP ପଠାଇବାରେ', resendOtp: 'ପୁନଃ OTP ପଠାନ୍ତୁ',
    },
    onboarding: {
      slide1Title: 'ପଣ୍ଡାର ସମାଜକୁ ସ୍ୱାଗତ',
      slide1Body: 'ଓଡ଼ିଶା ଭରିରେ ନିଖିଳ ଓଡ଼ିଶା ପଣ୍ଡାର ସମାଜର ୧୦,୦୦୦+ ସଦସ୍ୟଙ୍କ ସହ ଯୋଡ଼ି ହୁଅନ୍ତୁ।',
      slide2Title: 'ଆପଣଙ୍କ ପରିବାର, ସଂଯୁକ୍ତ',
      slide2Body: 'ସାମୁଦାୟିକ ସଦସ୍ୟ ତାଲିକା ଅନ୍ୱେଷଣ କରନ୍ତୁ। ଅନୁସରଣ କରନ୍ତୁ, ବାର୍ତ୍ତା ପଠାନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ଲୋକଙ୍କ ସହ ସଂଯୁକ୍ତ ରୁହନ୍ତୁ।',
      slide3Title: 'ଖବର ପାଆନ୍ତୁ',
      slide3Body: 'ସାମୁଦାୟିକ ଘୋଷଣା, ଅନୁଷ୍ଠାନ ଅପଡେଟ୍, ନେତାଙ୍କ ସମାଚାର ଏବଂ ବିବାହ ତାଲିକା — ସବୁ ଏକ ସ୍ଥାନରେ ପାଆନ୍ତୁ।',
      slide4Title: 'କେବଳ ସଦସ୍ୟଙ୍କ ପାଇଁ',
      slide4Body: 'ଆପଣଙ୍କ ପଞ୍ଜିକୃତ ମୋବାଇଲ ନମ୍ବର ସହ ଲଗଇନ କରନ୍ତୁ। ଆପଣଙ୍କ ତଥ୍ୟ ସୁରକ୍ଷିତ ଏବଂ କେବଳ ସାମୁଦାୟିକ ସଦସ୍ୟଙ୍କୁ ଦୃଶ୍ୟମାନ।',
      skip: 'ଏଡ଼ାଇ ଦିଅନ୍ତୁ', next: 'ପରବର୍ତ୍ତୀ →', getStarted: 'ଆରମ୍ଭ କରନ୍ତୁ',
    },
    announcements: {
      title: 'ଘୋଷଣା',
      officialUpdate: 'ସରକାରୀ ଅପଡେଟ୍',
      defaultTitle: 'ସରକାରୀ ଘୋଷଣା',
      loadError: 'ସରକାରୀ ଘୋଷଣା ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      emptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଘୋଷଣା ନାହିଁ',
      emptySubtitle: 'ଆଡମିନଙ୍କ ପକ୍ଷରୁ ସରକାରୀ ଅପଡେଟ୍ ପାଇଁ ପରେ ଯାଞ୍ଚ କରନ୍ତୁ।',
    },
    events: {
      title: 'ଅନୁଷ୍ଠାନ',
      communityEvents: 'ସାମୁଦାୟିକ କାର୍ଯ୍ୟକ୍ରମ',
      calendarSubtitle: 'ସମାଜ କାର୍ଯ୍ୟକ୍ରମ — Events Calendar',
      loadError: 'ସାମୁଦାୟିକ କାର୍ଯ୍ୟକ୍ରମ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      rsvpSuccessTitle: 'RSVP ପଞ୍ଜିକୃତ ହେଲା',
      rsvpSuccessMessage: 'ଏହି କାର୍ଯ୍ୟକ୍ରମ ପାଇଁ ସଫଳତାର ସହ ପଞ୍ଜିକୃତ ହେଲେ!',
      rsvpError: 'RSVP ପଞ୍ଜିକରଣ ଦାଖଲ କରିବାରେ ବିଫଳ।',
      tabUpcoming: 'ଆଗାମୀ', tabPast: 'ପୂର୍ବ କାର୍ଯ୍ୟକ୍ରମ', tabRsvped: 'ମୋର RSVP',
      locationTBA: 'ପରେ ଜଣାଇବେ',
      attending: 'ଉପସ୍ଥିତ',
      registered: '✓ ପଞ୍ଜିକୃତ',
      rsvpNow: 'RSVP କରନ୍ତୁ',
      noRsvpsTitle: 'କୌଣସି RSVP ନାହିଁ', noRsvpsSubtitle: 'ଆପଣ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି କାର୍ଯ୍ୟକ୍ରମରେ RSVP କରିନାହାଁନ୍ତି।',
      noUpcomingTitle: 'କୌଣସି ଆଗାମୀ କାର୍ଯ୍ୟକ୍ରମ ନାହିଁ', noUpcomingSubtitle: 'ପରେ ପୁଣି ଯାଞ୍ଚ କରନ୍ତୁ',
    },
    groups: {
      title: 'ସମାଜ ଗ୍ରୁପ୍ ଗୁଡିକ',
      loadError: 'ଗ୍ରୁପ୍ ତାଲିକା ଆଣିବାରେ ବିଫଳ',
      joinedTitle: 'ଗ୍ରୁପ୍‌ରେ ଯୋଗ ଦେଲେ!', leftTitle: 'ଗ୍ରୁପ୍ ଛାଡିଲେ!',
      joinedMessagePrefix: 'ଆପଣ', joinedMessageSuffix: 'ରେ ଯୋଗ ଦେଇଛନ୍ତି',
      leftMessagePrefix: 'ଆପଣ', leftMessageSuffix: 'ରୁ ବାହାରି ଯାଇଛନ୍ତି',
      searchPlaceholder: 'ଗ୍ରୁପ୍ ଖୋଜନ୍ତୁ...',
      verifiedGroup: 'ଯୋଗ୍ୟ ସଦସ୍ୟ',
      joined: 'ଯୋଗଦେଇଛନ୍ତି ✓', joinGroup: 'ଯୋଗ ଦିଅନ୍ତୁ',
      emptyTitle: 'କୌଣସି ଗ୍ରୁପ୍ ମିଳିଲା ନାହିଁ', emptySubtitle: 'ଅନ୍ୟ ସନ୍ଧାନ ସର୍ତ୍ତ ଚେଷ୍ଟା କରନ୍ତୁ',
      showAllGroups: 'ସମସ୍ତ ଗ୍ରୁପ୍ ଦେଖନ୍ତୁ',
      categoryAll: 'ସମସ୍ତ ଗ୍ରୁପ୍', categoryRegional: 'ଆଞ୍ଚଳିକ', categoryMatrimony: 'ବିବାହ',
      categoryYouth: 'ଯୁବକ', categorySocial: 'ସାମାଜିକ', categoryProfessional: 'ପେଶାଦାର',
    },
    leaders: {
      title: 'ନେତା',
      communityLeaders: 'ସମାଜ ନେତା',
      leadershipSubtitle: 'ସମାଜ ନେତୃତ୍ୱ — Leadership Tiers',
      levelState: 'State', levelStateOr: 'ରାଜ୍ୟ',
      levelDistrict: 'District', levelDistrictOr: 'ଜିଲ୍ଲା',
      levelTaluka: 'Taluka', levelTalukaOr: 'ତାଲୁକ',
      levelPanchayat: 'Panchayat', levelPanchayatOr: 'ପଞ୍ଚାୟତ',
      locationPrefix: 'ସ୍ଥାନ:', selectPrefix: 'ମନୋନୀତ କରନ୍ତୁ', choose: 'ମନୋନୀତ କରନ୍ତୁ ▾',
      loadingLeaders: 'ନେତାମାନଙ୍କୁ ଲୋଡ୍ କରାଯାଉଛି…',
      emptyTitle: 'କୌଣସି ନେତା ମିଳିଲେ ନାହିଁ', emptySubtitle: 'ଏହି ସ୍ତରରେ କୌଣସି ନେତା କାର୍ଡ ପଞ୍ଜିକୃତ ହୋଇନାହିଁ।',
      selectLocationTitle: 'ସ୍ଥାନ ମନୋନୀତ କରନ୍ତୁ', allPrefix: 'ସମସ୍ତ',
      searchPlaceholder: 'ନାମ, ପଦବୀ, କିମ୍ବା ସ୍ଥାନ ଅନୁସାରେ ଖୋଜନ୍ତୁ…',
      noSearchResultsTitle: 'କୌଣସି ମେଳ ମିଳିଲା ନାହିଁ', noSearchResultsSubtitle: 'ଅନ୍ୟ ନାମ, ପଦବୀ, କିମ୍ବା ସ୍ଥାନ ଚେଷ୍ଟା କରନ୍ତୁ।',
    },
    matrimony: {
      title: 'ବୈବାହିକ ପ୍ରସ୍ତାବ',
      verifiedBanner: 'ସମସ୍ତ ପ୍ରୋଫାଇଲ୍ ସମାଜ ଦ୍ୱାରା ଯାଞ୍ଚ ହୋଇଛି',
      filterAll: 'ସବୁ', filterBrides: 'ପାତ୍ରୀ ♀', filterGrooms: 'ପାତ୍ର ♂',
      groomTag: 'ପାତ୍ର ♂', brideTag: 'ପାତ୍ରୀ ♀',
      gotraLabel: 'ଗୋତ୍ର:',
      interestExpressedCard: 'ଆଗ୍ରହ ପଠାଯାଇଛି ✓', interestExpressedModal: 'ଆଗ୍ରହ ପଠାଯାଇଛି ✓',
      emptyTitle: 'କୌଣସି ପାତ୍ର/ପାତ୍ରୀ ମିଳିଲେ ନାହିଁ', emptySubtitle: 'ଅନ୍ୟ ଫିଲ୍ଟର ଚେଷ୍ଟା କରନ୍ତୁ',
      resetFilter: 'ଫିଲ୍ଟର୍ ରିସେଟ୍ କରନ୍ତୁ',
      profileDetailsHeader: 'ବ୍ୟକ୍ତିଗତ ବିବରଣୀ',
      heightLabel: 'ଉଚ୍ଚତା', educationLabel: 'ଶିକ୍ଷାଗତ ଯୋଗ୍ୟତା', occupationLabel: 'ବୃତ୍ତି / ଚାକିରି',
      parentsLabel: 'ପିତାମାତାଙ୍କ ପରିଚୟ', locationLabel: 'ସ୍ଥାନ',
      yearsAbbrev: 'ବର୍ଷ',
      sendInterest: 'ଆଗ୍ରହ ପ୍ରକାଶ କରନ୍ତୁ',
      shortlistAddedTitle: 'ପସନ୍ଦ ତାଲିକାରେ ଯୋଡ଼ାଗଲା', shortlistRemovedTitle: 'ପସନ୍ଦ ତାଲିକାରୁ ବାଦ୍ ଦିଆଗଲା',
      shortlistAddedMessagePrefix: '', shortlistAddedMessageSuffix: 'ଙ୍କୁ ଆପଣ ପସନ୍ଦ କରିଛନ୍ତି',
      shortlistRemovedMessagePrefix: '', shortlistRemovedMessageSuffix: 'ଙ୍କୁ ବାଦ୍ ଦିଆଯାଇଛି',
      interestExpressedToastTitle: 'ଆଗ୍ରହ ପ୍ରକାଶ ହେଲା!', interestRetractedToastTitle: 'ଆଗ୍ରହ ପ୍ରତ୍ୟାହାର ହେଲା',
      interestExpressedMessagePrefix: 'ଆପଣଙ୍କ ଅନୁରୋଧ', interestExpressedMessageSuffix: ' ଙ୍କ ପରିବାରକୁ ପଠାଗଲା।',
      interestCanceledMessagePrefix: 'ଆପଣ', interestCanceledMessageSuffix: 'ଙ୍କଠାରେ ଆଗ୍ରହ ପ୍ରତ୍ୟାହାର କଲେ',
    },
    members: {
      title: 'ସଦସ୍ୟ',
      loadError: 'ସଦସ୍ୟ ଲୋଡ୍ କରିବାରେ ବିଫଳ',
      searchPlaceholder: 'ନାମ · #ନମ୍ବର · ଗ୍ରାମ · ମୋବାଇଲ…',
      matchingPrefix: 'ମେଳ ହେଉଛି',
      countSuffix: 'ସଦସ୍ୟ',
      noMembersTitle: 'କୌଣସି ସଦସ୍ୟ ମିଳିଲେ ନାହିଁ',
      noMembersSubtitle: 'ଅନ୍ୟ ସନ୍ଧାନ ବା ଫିଲ୍ଟର ଚେଷ୍ଟା କରନ୍ତୁ',
      allLoadedPrefix: 'ସମସ୍ତ', allLoadedSuffix: 'ସଦସ୍ୟ ଲୋଡ୍ ହେଲେ',
      maleHof: '♂ ପୁରୁଷ ମୁଖ୍ୟ', femaleHof: '♀ ମହିଳା ମୁଖ୍ୟ',
      // Filter modal
      filterModalTitle: 'ସଦସ୍ୟ ଫିଲ୍ଟର୍ କରନ୍ତୁ',
      districtSectionTitle: 'ଜିଲ୍ଲା', talukaSectionTitle: 'ତାଲୁକ',
      panchayatSectionTitle: 'ପଞ୍ଚାୟତ', villageSectionTitle: 'ଗ୍ରାମ',
      genderSectionTitle: 'ପରିବାର ମୁଖ୍ୟଙ୍କ ଲିଙ୍ଗ',
      allDistricts: 'ସମସ୍ତ ଜିଲ୍ଲା',
      allTalukasInPrefix: 'ସମସ୍ତ ତାଲୁକ', allPanchayatsInPrefix: 'ସମସ୍ତ ପଞ୍ଚାୟତ', allVillagesInPrefix: 'ସମସ୍ତ ଗ୍ରାମ',
      allGenders: 'ସମସ୍ତ ଲିଙ୍ଗ', maleHead: '♂ ପୁରୁଷ ମୁଖ୍ୟ', femaleHead: '♀ ମହିଳା ମୁଖ୍ୟ',
      resetButton: 'ପୁନଃସେଟ୍',
      showResultsPrefix: 'ଦେଖନ୍ତୁ', showResultsSuffix: 'ଫଳାଫଳ',
      // Member card
      activeBadge: 'ସକ୍ରିୟ',
      headGenderTitle: 'ମୁଖ୍ୟଙ୍କ ଲିଙ୍ଗ',
      genderFemaleTag: '♀ ମହିଳା', genderMaleTag: '♂ ପୁରୁଷ',
      maleWord: 'ପୁରୁଷ', femaleWord: 'ମହିଳା',
      familyMembersListLabel: 'ପାରିବାରିକ ସଦସ୍ୟ ତାଲିକା',
    },
    memberProfile: {
      notFoundText: 'ପ୍ରୋଫାଇଲ୍ ମିଳିଲା ନାହିଁ କିମ୍ବା ପ୍ରତିବନ୍ଧିତ।',
      returnToMembers: '← ସଦସ୍ୟ ତାଲିକାକୁ ଫେରନ୍ତୁ',
      backLabel: '← ପଛକୁ',
      followingLabel: 'ଅନୁସରଣ କରୁଛନ୍ତି', followLabel: 'ଅନୁସରଣ କରନ୍ତୁ', messageLabel: 'ବାର୍ତ୍ତା',
      headOfFamily: 'ପରିବାର ମୁଖ୍ୟ',
      joinedPrefix: 'ଯୋଗ ଦେଲେ',
      postsTabLabel: 'ପୋଷ୍ଟ', familyTabLabel: 'ପରିବାର', galleryTabLabel: 'ଗ୍ୟାଲେରୀ',
      statsFollowersLabel: 'ଅନୁସରଣକାରୀ',
      familyMembersHeader: 'ପାରିବାରିକ ସଦସ୍ୟ',
      noPostsTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପୋଷ୍ଟ ନାହିଁ', noPostsSubtitle: 'ଏହି ସଦସ୍ୟ ଏପର୍ଯ୍ୟନ୍ତ ପୋଷ୍ଟ କରିନାହାଁନ୍ତି',
      noPhotosTitle: 'କୌଣସି ଫଟୋ ନାହିଁ', noPhotosSubtitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଟୋ ସେୟାର ହୋଇନାହିଁ',
    },
    profile: {
      title: 'ମୋର ପ୍ରୋଫାଇଲ୍',
      settingsButton: 'ସେଟିଂ',
      memberBadge: 'ପଣ୍ଡାର ସଦସ୍ୟ',
      headOfFamily: 'ପରିବାର ମୁଖ୍ୟ',
      mobilePrefix: 'ମୋବାଇଲ:',
      familyHubHeader: 'ପାରିବାରିକ କେନ୍ଦ୍ର',
      familyTreeLabel: 'ପାରିବାରିକ ବଂଶାବଳୀ', familyTreeDesc: 'ବଂଶାବଳୀ ବୃକ୍ଷ',
      matrimonyLabel: 'ବିବାହ', matrimonyDesc: 'ମେଳ ଖୋଜନ୍ତୁ',
      familyAlbumsLabel: 'ପାରିବାରିକ ଆଲବମ୍', familyAlbumsDesc: 'ସେୟାର ହୋଇଥିବା ଗ୍ୟାଲେରୀ',
      familyEventsLabel: 'ପାରିବାରିକ କାର୍ଯ୍ୟକ୍ରମ', familyEventsDesc: 'RSVP ହୋଇଥିବା କାର୍ଯ୍ୟକ୍ରମ',
      addressInfoHeader: 'ଠିକଣା ସୂଚନା',
      villageLabel: 'ଗ୍ରାମ', panchayatLabel: 'ପଞ୍ଚାୟତ', fullAddressLabel: 'ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା',
      notSpecified: 'ଉଲ୍ଲେଖ ହୋଇନାହିଁ',
      villagePlaceholder: 'ଗ୍ରାମ ନାମ', panchayatPlaceholder: 'ପଞ୍ଚାୟତ ନାମ', addressPlaceholder: 'ସମ୍ପୂର୍ଣ୍ଣ ଠିକଣା ବିବରଣୀ',
      familyMembersHeader: 'ପାରିବାରିକ ସଦସ୍ୟ',
      noFamilyMembers: 'କୌଣସି ପାରିବାରିକ ସଦସ୍ୟ ପଞ୍ଜିକୃତ ହୋଇନାହାଁନ୍ତି।',
      yrsAbbrev: 'ବର୍ଷ',
      profilePhotoTitle: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ', profilePhotoMessage: 'ଆପଣଙ୍କ ପ୍ରୋଫାଇଲ୍ ଫଟୋ ବଦଳାନ୍ତୁ କିମ୍ବା ହଟାନ୍ତୁ।',
      removePhoto: 'ଫଟୋ ହଟାନ୍ତୁ', removedTitle: 'ହଟାଗଲା', removedMessage: 'ପ୍ରୋଫାଇଲ୍ ଫଟୋ ହଟାଗଲା।',
      uploadNewPhoto: 'ନୂଆ ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ', uploadTitle: 'ଅପଲୋଡ୍', uploadMessage: 'ଫଟୋ ଅପଲୋଡ୍ ସିମୁଲେଟ୍ ହେଲା।',
      profileSavedTitle: 'ପ୍ରୋଫାଇଲ୍ ସେଭ୍ ହେଲା', profileSavedMessage: 'ଆପଣଙ୍କ ଠିକଣା ବିବରଣୀ ଅପଡେଟ୍ ହୋଇଛି।',
    },
    familyTree: {
      title: 'ପାରିବାରିକ ବଂଶ ବୃକ୍ଷ',
      subtitle: 'ଆପଣଙ୍କ ପରିବାର, ଏକ ନଜରରେ',
      headOfFamily: 'ପରିବାର ମୁଖ୍ୟ',
      membershipPrefix: 'ସଦସ୍ୟତା #',
      groupSpouse: 'ପତି/ପତ୍ନୀ',
      groupParents: 'ପିତାମାତା',
      groupChildren: 'ସନ୍ତାନ',
      groupOthers: 'ଅନ୍ୟ ପାରିବାରିକ ସଦସ୍ୟ',
      ageSuffix: 'ବର୍ଷ',
      emptyTitle: 'କୌଣସି ପାରିବାରିକ ତଥ୍ୟ ନାହିଁ',
      emptySubtitle: 'ଆପଣଙ୍କ ପାରିବାରିକ ବିବରଣୀ ଏପର୍ଯ୍ୟନ୍ତ ପ୍ରୋଫାଇଲ୍‌ରେ ଯୋଡ଼ାଯାଇ ନାହିଁ।',
    },
    familyAlbums: {
      title: 'ପାରିବାରିକ ଆଲବମ',
      subtitle: 'ଆପଣଙ୍କ ପରିବାର ମଧ୍ୟରେ ସେୟାର ହୋଇଥିବା ଫଟୋ',
      loadError: 'ପାରିବାରିକ ଆଲବମ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      createAlbum: 'ଆଲବମ ତିଆରି କରନ୍ତୁ',
      newAlbumTitle: 'ନୂଆ ଆଲବମ',
      albumTitleLabel: 'ଶୀର୍ଷକ',
      albumTitlePlaceholder: 'ଯଥା ଦୀପାବଳି ୨୦୨୫',
      albumDescriptionLabel: 'ବିବରଣୀ',
      albumDescriptionPlaceholder: 'ଏକ ସଂକ୍ଷିପ୍ତ ବିବରଣୀ ଯୋଡ଼ନ୍ତୁ (ଇଚ୍ଛାଧୀନ)',
      coverPhotoLabel: 'କଭର ଫଟୋ (ଇଚ୍ଛାଧୀନ)',
      chooseCoverPhoto: 'କଭର ଫଟୋ ବାଛନ୍ତୁ',
      changeCoverPhoto: 'କଭର ଫଟୋ ବଦଳାନ୍ତୁ',
      createButton: 'ଆଲବମ ତିଆରି କରନ୍ତୁ',
      creatingButton: 'ତିଆରି ହେଉଛି…',
      titleRequiredError: 'ଦୟାକରି ଏକ ଆଲବମ ଶୀର୍ଷକ ପ୍ରବେଶ କରନ୍ତୁ।',
      createError: 'ଆଲବମ ତିଆରି କରିବାରେ ବିଫଳ।',
      createSuccessTitle: 'ଆଲବମ ତିଆରି ହେଲା',
      createSuccessMessage: 'ଆପଣଙ୍କ ନୂଆ ପାରିବାରିକ ଆଲବମ ପ୍ରସ୍ତୁତ ଅଛି।',
      photosCountSuffix: 'ଫଟୋ',
      photoCountSingular: 'ଫଟୋ',
      emptyTitle: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଆଲବମ ନାହିଁ',
      emptySubtitle: 'ଫଟୋ ସେୟାର କରିବା ଆରମ୍ଭ କରିବାକୁ ଆପଣଙ୍କ ପ୍ରଥମ ଆଲବମ ତିଆରି କରନ୍ତୁ।',
      deleteAlbumConfirmTitle: 'ଆଲବମ ଡିଲିଟ୍ କରନ୍ତୁ',
      deleteAlbumConfirmMessage: 'ଏହା ଏହି ଆଲବମ ଏବଂ ଏଥିରେ ଥିବା ସମସ୍ତ ଫଟୋକୁ ସ୍ଥାୟୀ ଭାବରେ ଡିଲିଟ୍ କରିଦେବ। ଜାରି ରଖିବେ କି?',
      deleteError: 'ଆଲବମ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ।',
      deleteSuccessMessage: 'ଆଲବମ ଡିଲିଟ୍ ହୋଇଗଲା।',
      addPhotos: 'ଫଟୋ ଯୋଡ଼ନ୍ତୁ',
      addingPhotos: 'ଅପଲୋଡ୍ ହେଉଛି…',
      addPhotosError: 'ଫଟୋ ଯୋଡ଼ିବାରେ ବିଫଳ।',
      addPhotosSuccessMessage: 'ଫଟୋ ଆଲବମ୍‌ରେ ଯୋଡ଼ାଗଲା।',
      noPhotosInAlbum: 'ଏହି ଆଲବମ୍‌ରେ ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ଫଟୋ ନାହିଁ।',
      cancelButton: 'ବାତିଲ',
      closeButton: 'ବନ୍ଦ କରନ୍ତୁ',
    },
    familyEvents: {
      title: 'ପାରିବାରିକ ଅନୁଷ୍ଠାନ',
      subtitle: 'ଆପଣଙ୍କ ନିଜ ପରିବାର ପାଇଁ ଅନୁଷ୍ଠାନ',
      loadError: 'ପାରିବାରିକ ଅନୁଷ୍ଠାନ ଲୋଡ୍ କରିବାରେ ବିଫଳ।',
      createEvent: 'ଅନୁଷ୍ଠାନ ତିଆରି କରନ୍ତୁ',
      newEventTitle: 'ନୂଆ ପାରିବାରିକ ଅନୁଷ୍ଠାନ',
      eventTitleLabel: 'ଶୀର୍ଷକ',
      eventTitlePlaceholder: 'ଯଥା ଜେଜେମାଙ୍କ ଜନ୍ମଦିନ',
      descriptionLabel: 'ବିବରଣୀ',
      descriptionPlaceholder: 'ବିବରଣୀ ଯୋଡ଼ନ୍ତୁ (ଇଚ୍ଛାଧୀନ)',
      dateLabel: 'ତାରିଖ',
      datePlaceholder: 'YYYY-MM-DD',
      locationLabel: 'ସ୍ଥାନ',
      locationPlaceholder: 'ଏହା କେଉଁଠାରେ ହେବ?',
      typeLabel: 'ପ୍ରକାର',
      typePlaceholder: 'ଯଥା ଜନ୍ମଦିନ, ବାର୍ଷିକୀ, ସମାବେଶ',
      createButton: 'ଅନୁଷ୍ଠାନ ତିଆରି କରନ୍ତୁ',
      creatingButton: 'ତିଆରି ହେଉଛି…',
      titleRequiredError: 'ଦୟାକରି ଏକ ଅନୁଷ୍ଠାନ ଶୀର୍ଷକ ପ୍ରବେଶ କରନ୍ତୁ।',
      dateRequiredError: 'ଦୟାକରି ଏକ ବୈଧ ତାରିଖ (YYYY-MM-DD) ପ୍ରବେଶ କରନ୍ତୁ।',
      createError: 'ଅନୁଷ୍ଠାନ ତିଆରି କରିବାରେ ବିଫଳ।',
      createSuccessTitle: 'ଅନୁଷ୍ଠାନ ତିଆରି ହେଲା',
      createSuccessMessage: 'ଆପଣଙ୍କ ପାରିବାରିକ ଅନୁଷ୍ଠାନ ଯୋଡ଼ାଗଲା।',
      emptyTitle: 'କୌଣସି ପାରିବାରିକ ଅନୁଷ୍ଠାନ ନାହିଁ',
      emptySubtitle: 'ଆପଣଙ୍କ ପରିବାର ସହ ଯୋଜନା ଆରମ୍ଭ କରିବାକୁ ଏକ ଅନୁଷ୍ଠାନ ତିଆରି କରନ୍ତୁ।',
      deleteEventConfirmTitle: 'ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ କରନ୍ତୁ',
      deleteEventConfirmMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଏହି ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      deleteError: 'ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ କରିବାରେ ବିଫଳ।',
      deleteSuccessMessage: 'ଅନୁଷ୍ଠାନ ଡିଲିଟ୍ ହୋଇଗଲା।',
      tabUpcoming: 'ଆଗାମୀ',
      tabPast: 'ପୂର୍ବ',
      rsvpGoing: 'ଯିବି',
      rsvpMaybe: 'ହୁଏତ',
      rsvpNotGoing: 'ଯିବି ନାହିଁ',
      rsvpError: 'RSVP ଦାଖଲ କରିବାରେ ବିଫଳ।',
      locationTBA: 'ପରେ ଜଣାଇବେ',
      cancelButton: 'ବାତିଲ',
    },
    explore: {
      title: 'ଅନ୍ୱେଷଣ',
      tabTrending: 'ଟ୍ରେଣ୍ଡିଂ', tabMembers: 'ସଦସ୍ୟ', tabHashtags: 'ହ୍ୟାସ୍‌ଟାଗ୍',
      trendingPostsTitle: 'ଟ୍ରେଣ୍ଡିଂ ପୋଷ୍ଟ',
      trendingPostsSubtitle: 'ସମାଜରେ ସର୍ବାଧିକ ଆଲୋଚିତ ପୋଷ୍ଟ। (ଶୀଘ୍ର ଆସୁଛି)',
      activeMembersLabel: 'ଆଜି ସକ୍ରିୟ ମୋଟ ସଦସ୍ୟ',
      noPopularMembers: 'କୌଣସି ଲୋକପ୍ରିୟ ସଦସ୍ୟ ତଥ୍ୟ ଉପଲବ୍ଧ ନାହିଁ।',
      noTags: 'ବର୍ତ୍ତମାନ କୌଣସି ଟ୍ୟାଗ୍ ଉପଲବ୍ଧ ନାହିଁ।',
    },
    feedComponents: {
      warningTitle: 'ଚେତାବନୀ',
      inappropriateCommentMessage: 'ଆପଣଙ୍କ ମନ୍ତବ୍ୟରେ ଅନୁପଯୁକ୍ତ ବିଷୟବସ୍ତୁ ଅଛି।',
      cancelButtonLabel: 'ବାତିଲ',
      saveButtonLabel: 'ସେଭ୍',
      deleteButtonLabel: 'ଡିଲିଟ୍',
      commentWord: 'ମନ୍ତବ୍ୟ',
      commentsWordPlural: 'ମନ୍ତବ୍ୟ',
      likeLabel: 'ଲାଇକ୍',
      likedLabel: 'ଲାଇକ୍ ହୋଇଛି',
      replyLabel: 'ଉତ୍ତର',
      writeReplyPlaceholder: 'ଉତ୍ତର ଲେଖନ୍ତୁ...',
      noCommentsYetText: 'ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ମନ୍ତବ୍ୟ ନାହିଁ',
      loadMoreCommentsLabel: 'ଅଧିକ ମନ୍ତବ୍ୟ ଲୋଡ୍ କରନ୍ତୁ',
      writeCommentPlaceholder: 'ମନ୍ତବ୍ୟ ଲେଖନ୍ତୁ...',
      editPostLabel: 'ପୋଷ୍ଟ ଏଡିଟ୍ କରନ୍ତୁ',
      deletePostLabel: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ',
      savePostLabel: 'ପୋଷ୍ଟ ସେଭ୍ କରନ୍ତୁ',
      unsavePostLabel: 'ପୋଷ୍ଟ ଅନ୍‌ସେଭ୍ କରନ୍ତୁ',
      reportPostLabel: 'ପୋଷ୍ଟ ରିପୋର୍ଟ କରନ୍ତୁ',
      deletePostConfirmTitle: 'ପୋଷ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ',
      deletePostConfirmMessage: 'ଆପଣ ନିଶ୍ଚିତ ଭାବରେ ଏହି ପୋଷ୍ଟ ଡିଲିଟ୍ କରିବାକୁ ଚାହୁଁଛନ୍ତି କି?',
      reportPostModalTitle: 'ପୋଷ୍ଟ ରିପୋର୍ଟ କରନ୍ତୁ',
      reportPostPrompt: 'ଆପଣ ଏହି ପୋଷ୍ଟକୁ କାହିଁକି ରିପୋର୍ଟ କରୁଛନ୍ତି?',
      submitReportLabel: 'ରିପୋର୍ଟ ଦାଖଲ କରନ୍ତୁ',
      reportReasonAdult: 'ବୟସ୍କ / ଯୌନ ବିଷୟବସ୍ତୁ',
      reportReasonHarassment: 'ହଇରାଣ ବା ଧମକ',
      reportReasonHateSpeech: 'ଘୃଣା ବକ୍ତବ୍ୟ',
      reportReasonSpam: 'ସ୍ପାମ୍ କିମ୍ବା ଭ୍ରାନ୍ତିଜନକ',
      reportReasonViolence: 'ହିଂସା କିମ୍ବା ବିପଦଜନକ ବିଷୟବସ୍ତୁ',
      reportReasonFalseInfo: 'ଭୁଲ ସୂଚନା',
      reportReasonOther: 'ଅନ୍ୟାନ୍ୟ',
      sharePostTitlePrefix: 'ପୋଷ୍ଟ କରିଛନ୍ତି',
      genericErrorTitle: 'ତ୍ରୁଟି',
      postValidationErrorMessage: 'ଦୟାକରି କିଛି ଟେକ୍ସଟ୍ କିମ୍ବା ମିଡିଆ/ପୋଲ୍ ଯୋଡ଼ନ୍ତୁ।',
      inappropriateContentTitle: 'ଅନୁପଯୁକ୍ତ ବିଷୟବସ୍ତୁ',
      inappropriateContentMessage: 'ଆପଣଙ୍କ ପୋଷ୍ଟରେ ପ୍ରତିବନ୍ଧିତ ଶବ୍ଦ ଅଛି।',
      shareSomethingPlaceholder: 'ସମାଜ ସହ କିଛି ସେୟାର କରନ୍ତୁ...',
      createPostTitle: 'ପୋଷ୍ଟ ତିଆରି କରନ୍ତୁ',
      postButtonLabel: 'ପୋଷ୍ଟ',
      postingToMemberPortal: 'ସଦସ୍ୟ ପୋର୍ଟାଲକୁ ପୋଷ୍ଟ କରୁଛନ୍ତି',
      whatsOnYourMindPlaceholder: 'ଆପଣଙ୍କ ମନରେ କଣ ଅଛି? (#ଟ୍ୟାଗ୍ କିମ୍ବା @ମେନ୍‌ସନ୍ ବ୍ୟବହାର କରନ୍ତୁ)',
      enterLocationPlaceholder: 'ସ୍ଥାନ ଟ୍ୟାଗ୍ ପ୍ରବେଶ କରନ୍ତୁ...',
      createPollTitle: 'ପୋଲ୍ ତିଆରି କରନ୍ତୁ',
      pollLimitReachedTitle: 'ସୀମା ପହଞ୍ଚିଲା',
      pollLimitReachedMessage: 'ଆପଣ ସର୍ବାଧିକ ୫ଟି ବିକଳ୍ପ ଯୋଡ଼ି ପାରିବେ।',
      pollMinOptionsTitle: 'ଆବଶ୍ୟକ',
      pollMinOptionsMessage: 'ଏକ ପୋଲ୍ ପାଇଁ ଅତିକମରେ ୨ଟି ବିକଳ୍ପ ଆବଶ୍ୟକ।',
      pollQuestionRequiredMessage: 'ଦୟାକରି ଏକ ପୋଲ୍ ପ୍ରଶ୍ନ ପ୍ରବେଶ କରନ୍ତୁ।',
      pollOptionsRequiredMessage: 'ଦୟାକରି ଅତିକମରେ ୨ଟି ବୈଧ ବିକଳ୍ପ ପ୍ରବେଶ କରନ୍ତୁ।',
      pollQuestionLabel: 'ପ୍ରଶ୍ନ',
      pollQuestionPlaceholder: 'ଆପଣ କଣ ପଚାରିବାକୁ ଚାହୁଁଛନ୍ତି?',
      pollOptionsLabel: 'ବିକଳ୍ପ',
      pollOptionPlaceholderPrefix: 'ବିକଳ୍ପ',
      addOptionLabel: 'ବିକଳ୍ପ ଯୋଡ଼ନ୍ତୁ',
      createButtonLabel: 'ତିଆରି କରନ୍ତୁ',
      voteWord: 'ଭୋଟ୍',
      votesWordPlural: 'ଭୋଟ୍',
      pollEndsPrefix: 'ସମାପ୍ତ',
      addStoryLabel: 'ଷ୍ଟୋରୀ ଯୋଡ଼ନ୍ତୁ',
    },
  },
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (section: string, key: string) => string;
}

const LanguageContext = createContext<LangContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>('en');

  useEffect(() => {
    storage.getItem(STORAGE_KEYS.LANGUAGE).then((saved) => {
      if (saved === 'en' || saved === 'od') setLangState(saved);
    });
  }, []);

  const setLang = async (l: Lang) => {
    setLangState(l);
    await storage.setItem(STORAGE_KEYS.LANGUAGE, l);
  };

  const t = (section: string, key: string): string => {
    return (translations[lang] as any)?.[section]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
